### ISSUE TITLE
Frequencies for histogram

### ISSUE THREAD

**Issue by RinkHoekstra** [jasp-stats/jasp-desktop#1036]
In JASP, a variable can be visually displayed by clicking "Display plot", or "Display Correlation Plot". Both plots present a similar histogram for continuous data, with one plot being a stretched and larger version of the other. The histogram also shows some curve that is meant to fit the data. The y-axis shows only the word "density", whereas I would expect this to show frequencies, given that it's a histogram. Could there be an option to display frequencies for the histogram? And maybe the option to toggle the density curve on/off?

**Comment by vankesteren** [comment]
Hello Rink,

__for continuous variables:__
the bins chosen are 'arbitrary' , i.e. chosen through an algorithm that assigns optimal widths. This means that the frequency values also will be 'arbitrary': if the bin widths would change by using a different algorithm, the frequencies would also change. The y-axis, therefore, represents only exactly a _density_, which is why that is indicated there.

__for categorical variables:__
the bins here are most definitely _not_ arbitrary, hence here the y-axis does show the frequency and not the density curve either.

A solution to your problem would be to convert your continuous variable to categorical using _non-arbitrary_ categories. In the newest `JASP` version, you can do this in your spreadsheet editor of choice and immediately see the results.

I'll close the issue for now.

Erik-Jan
