### ISSUE TITLE
feature request: y labels for repeated-measures designs

### ISSUE THREAD

**Issue by lvanderlinden** [jasp-stats/jasp-desktop#1114]
Hi everyone,

First off, thank you so much for this wonderful software!

I noticed that the descriptive plots of repeated measures designs (both t-tests and ANOVAs) do not have (the possibility to specify) a y label. The same is true for the x axis of descriptive plots of the paired-samples t-test.

I was wondering whether it would be possible to implement the possibility to add these labels, for example by having a box where the user can fill in the name of the DV (and the IV, for the paired-samples t-test).

The reason I'm asking is because I plan to use JASP for a statistics course, and for pedagogical reasons I would prefer my students to save plots with all the information in it.

I'm using JASP 0.7.5 Beta 2 under Ubuntu 15.10

Best wishes,

Lotje

**Comment by raviselker** [comment]
Hi Lotje,

Thanks for your suggestion! I agree, this is definitely something we should add. We'll try to think of a way to add this sooner rather than later.

Great that you want to use JASP for a statistics course! We are planning to put a lot of focus on JASP as a teaching tool. So if you have any more suggestions, please let us know.

Cheers,
Ravi

**Comment by boutinb** [comment]
We can now edit labels in 8.1.0. Is this what you want?
