### ISSUE TITLE
Fluctuation in Bayes-Factor

### ISSUE THREAD

**Issue by dansom** [jasp-stats/jasp-desktop#1126]
Dear JASP-Team,

first of all thanks for your great work, your efforts and the wonderful program JASP! Even without the Bayesian-Analysis features it is way nicer than SPSS since it is so lightweight and fast! The only thing that I'm really really missing right now is data editing, but I've heard you're working on this :-)

While exploring JASP (I'm quite new to Bayesian-Analysis and JASP) I conducted a Bayesian T-Test on the Kitchen-Rolls Dataset (dependent Variable: mean_NEO and grouping variable: rotation) with a "Group 1 > Group 2" hypotheses and set the output to BF01.
If I do so and let JASP (version calculate the value several times (eg by switching to another hypotheses and back) the Basefactor slightly changes (e.g. 7.758;7.750;7.746). This also happens with the "Group 1 < Group 2" hypotheses but not with "Group 1 /= Group 2". Funnily enough this also does not seem to happen when I look at BF10.
From my observations I would guess, that this is some error in the approximation using a non-symmetric prior. Yet the stated error in the output is too small to really cause changes in the Basefactor-output.

I'm using JASP 0.7.1.12 on Mac OS X 10.11.

All the best and thanks for your efforts,

Daniel

P.S. Attached you can find three screenshots.

![1](https://cloud.githubusercontent.com/assets/16814024/12474723/8d0922a0-c01d-11e5-84c9-0e720c27ebca.png)
![2](https://cloud.githubusercontent.com/assets/16814024/12474721/8cd40fe8-c01d-11e5-9221-906c0fff84db.png)
![3](https://cloud.githubusercontent.com/assets/16814024/12474722/8cd76d78-c01d-11e5-98d5-724557dcc0f0.png)

**Comment by raviselker** [comment]
@quentingronau or @EJWagenmakers ?

**Comment by EJWagenmakers** [comment]
Hi Daniel,

Thanks for your positive comments about JASP. We are dedicated to improve and expand the program (and yes, data editing is one of our top priorities :-)). You are right that the one-sided test gives slightly different outcomes each time. The reason is that we can get BF_10 exactly (well, almost exactly) and then we estimate a correction factor to obtain the one-sided test (the gory details are here: http://www.ejwagenmakers.com/2014/MoreyWagenmakers2014.pdf). The correction factor is the posterior proportion lower then zero, and we estimate it using the MCMC samples. Because it is based on MCMC, there is a **slightly** different outcome each time.

Also, just to keep you in the loop, we are organizing a JASP workshop in August (https://jasp-stats.org/upcoming-events/jasp-workshop/), and there is JASP forum for general questions (http://forum.cogsci.nl/index.php?p=/categories/jasp-bayesfactor). If you'd like to continue discussing this topic I think that the forum is the right place for it!

Cheers,
E.J.

**Comment by dansom** [comment]
Hi E.J.,

thanks for your fast response and the info about the approximation you're using for the one-sided test. Since I have a maths background, the gory details were actually quite interesting, although I only understood parts of it since my background on Bayesian-statistics is still weak ;-)
I now also understand why there is a ~ in front of the "error%" when computing a one-sided test.

Thanks again for your and your colleagues work,

Daniel
