### ISSUE TITLE
Bayesian ANOVA: Produces uninformative error when infinities in dependent

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#116]

**Comment by mmarsman1** [comment]
@jonathon-love take a look at the below list of error messages
If you have any suggestions, please let me know. 
Otherwise I will include them in the next commit.

Least Squares Error Messages
FROM: 	Nonpositive weights encountered in [name of weight variable]
TO: 	Least squares regression model undefined -- there are nonpositive weights encountered

FROM:	Infinities encountered in [list of variable names here]
TO: 	Least squares regression model is undefined -- the dependent variable contains infinity
OR: 	Least squares regression model undefined -- one or more independent variables contain infinity
 
FROM: 	No valid cases observed after listwise deletion of missing values.
TO: 	The dependent variable has no observations. (Possibly only after rows with missing values are excluded)

FROM:	No variance in dependent variable.
TO: 	Least squares regression model is undefined -- the dependent variable contains all the same value (the variance is zero)
 
FROM:	No variance in independent variable: [variable name]
FROM:	No variance in independent variable(s): [list of variable names]
TO: 	Least squares regression model is undefined -- one or more of the independent variables contain all the same value (the 	variance is zero)

And in Bayesian Anova / Ancova:
 
FROM:	Interactions as nuisance are only allowed when the 	corresponding main effects are specified as nuisance
TO:	The main effects of variables should be specified as nuisance whenever their interaction is specified as nuisance

FROM:  	Interactions are only allowed when the corresponding main effects are specified
TO:	The main effects of variables should be included whenever their interaction is included

FROM:	Factors must have 2 or more levels
TO:	Factors must have 2 or more levels

FROM: 	After removing cases with missing values, less than 2 levels were observed for: [list of variable names here]
TO: 	Factor(s): [list of names] contain(s) less than two levels. (Possibly only after rows with missing values are excluded)

FROM:	All modelterms are specified as nuisance
TO:	BayesFactor is undefined -- all effects are specified as nuisance


FROM:	There needs to be at least one more (valid) observation than there are effects specified in the model
TO:	There needs to be at least one more (valid) observation than there are effects specified in the model

**Comment by jonathon-love** [comment]
the best way to discuss this would be to edit the error list document, and include that with the pull request. that way we can either discuss it there, (and perhaps i would propose changes), or i can just pull it and we can figure it out later.

sounds good?
