### ISSUE TITLE
Save output as pdf

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1205]
Question from a friend: "How can you print a pdf of the jasp results window?"
I think such functionality would be useful (no clue how much work it is) -- the main idea is that you might want to show/print your analyses outcomes but without presenting the entire .jasp file.

**Comment by boutinb** [comment]
You can always export as HTML. Is it not what you want?

**Comment by akashrajkn** [comment]
@EJWagenmakers I made this with Frans and Bruno's help last year.

While the functionality works well for most of the cases, the export to pdf does not work well for tables with many columns (length of table exceeds the page size - A4). Hence, I did not make a pull request for this feature. (See attached pdf)

Adding the pdf feature in itself isn't that complicated (Qt already gives support for this - [link](https://wiki.qt.io/Exporting_a_document_to_PDF)). The challenge is to overcome the above mentioned case.
 

[adsf-2.pdf](https://github.com/jasp-stats/jasp-desktop/files/842489/adsf-2.pdf)

**Comment by dietrichstats** [comment]
PSPP includes several export formats for output, however, the width of the tables is a problem as @akashrajkn says, however, an export format alternative to HTML is a good idea.

With the experience with PSPP a text document is not the best (*.odt), but a spreadsheet (*.ods) could be ideal, since you can keep the tables, comments and plots* (as images) for later editing and create a report directly, export it to PDF or print (#2302). The use case here is where a considerable amount of analysis is done and copying/pasting from JASP to word processor becomes counterproductive.

*remember that PSPP developers expected to be able to export tables and plots directly to OpenDocument *.odt format, but the second one turned out to be complex and not implemented.

**Comment by boutinb** [comment]
Thanks to our upgrade to Qt 5.10, we can now directly use the printToPdf function embedded in the WebEngine. I have just tried it, and it gives really good results. We will add this functionality to our next release

**Comment by AlexanderLyNL** [comment]
https://jasp-stats.org/download/
