### ISSUE TITLE
Feature Request: Closer integration of JASP and R

### ISSUE THREAD

**Issue by jeromyanglim** [jasp-stats/jasp-desktop#1220]
Hi,
I think JASP is great initiative. 

I just wanted to share a vision of what JASP could be if it was more integrated with R. I realise this goes against a few things you mention in the FAQ. But I think the approach would (a) be more reproducible, (b) reduce your need to reinvent the wheel, (c) provide a migration pathway to a more powerful tool, and (d) open up your novel functionality in JASP to greater scripting.

Here are the thoughts:
- In general, some form of scripting seems essential for any reproducible software. Such a script should be able to reproduce all analyses that the user runs, and it should be possible to rerun the analyses. SPSS has syntax (as well as other programming languages). Matlab, R, Stata, etc all have a scripting option that allows you to re-run analyses. Thus, presumably, SASP needs a scripting language that the user can see and run.
- I think it would be better if JASP produced R code that could be run either in JASP or R. Perhaps this reflects my own preference for R. But ultimately, R is a powerful open source statistical language. Some user needs may be met by JASP (i.e., you need to run a quick bayesian t-test) and functionality is clearly expanding, but I imagine that very quickly people would need a more powerful tool for data manipulation, graphing, and so on. Tighter integration with R would allow people to migrate to a more sophisticated tool. 
- R needs a better GUI front-end. There is Rcmdr, but it is a little bit clunky. The world of R desperately needs a high quality GUI front end that encourages scripting but allows people to use menus to generate scripts.
- Presumably, if JASP produced R code that was then run to produce output this would also open up the novel functionality to R users as a package.
- Making JASP a more general GUI front end for R might motivate others in the open source community to contribute more.

**Comment by stephensrmmartin** [comment]
Look into rkward and deducer.  Deducer is very similar to spss.

**Comment by jdittrich** [comment]
While I totally understand your reasoning, I assume that JASP is heading in another direction. 

Like @stephensrmmartin suggested, you could take a look at [RKWard](https://rkward.kde.org/). It provides GUI and code (and shows you the code the GUI sends to R) and has a plugin infrastructure in case you want to implement or share your own functionality.

**Comment by YourBrain** [comment]
I agree with Jeromy. One stated goal of JASP is to provide an alternative to SPSS but until we can replace the whole of SPSS, universities can't stop paying for it. JASP on its own falls a long way short. R does replace the whole of SPSS.  But it's not exactly user-friendly. A migration path is very important

I am curious what JASP developers think about RKWard and Deducer? Does seem to be lot of redundancy here.

**Comment by santsang** [comment]
I love R for one more reason - it pushes me to learn statistics properly.  GUI programmes do not drive us to consult the manual and seek explanations for using alternative settings.  Also, the scripts per se are records of the procedures.  We can verify our mistakes.

Sandro

**Comment by AlexanderLyNL** [comment]
We also love R and we also hope that people learn statistics properly. The integration with R code is on its way, but requires some changes to the current architecture and more time.

**Comment by EJWagenmakers** [comment]
In my opinion, there is little distinction between typing "t.test" using the keyboard or clicking a button "t-test" using the mouse. Statistical understanding comes from knowing what happens if you execute a particular command, regardless of the specifics of the input medium. Also, I'd like to stress that the analyses in JASP are fully reproducible. That said, the explicit integration with R is well on its way -- several JASP team members are working on it, one of them full-time. 
Cheers,
E.J.

**Comment by santsang** [comment]
We know that interface does change user behaviours.  We also know that SPSS
are designed for someone who are not necessarily rigourously trained in
stat.  Sandro

**Comment by AlexanderLyNL** [comment]
Hi Sandro,

Not all empirical scientists might have the time or the resources to learn R and are, thus, bounded by what expensive software packages offer. For instance, not all of the available software packages offer Bayesian methods, or network analyses, but we do offer them for free. Hence, “in the olden days” clinical psychologists who wanted to do a network analysis, but couldn’t use R, were unable to do so. Furthermore, the clinical psychologists who were running network analyses in R, were also not necessarily rigorously trained in statistics either. Nor does running R scripts necessarily made them understand statistics better. This does not mean that they won’t improve. The same can be said about the Bayesian analyses. 

The use of R (or JASP) itself doesn’t imply that you are, or will be, rigorously trained in statistics. Similarly, the use of a type writer, or keyboard, or an tablet doesn’t determine whether you are, or will be, a good writer. Nor does driving a manual or an automatic make you a responsible driver. 

People are developing and JASP is made to help these people. To do so, we also write blog posts explaining the theory, books, organise workshops, and publish papers open access so everyone can read them. Some of our users will become well-trained statisticians and some of them will use R, and perhaps delve deeper into the mathematics and develop new methods. We cannot force our users to become statisticians, but we can make it easier for them to become one. 

Of course, the integration between JASP and R, the books and the blog posts should all have been finished yesterday, but this takes time and effort. The program is open-source, so you’re welcome to contribute. To tell empirical scientists that they aren’t able to use certain methods, because they are not (yet) rigorously trained in statistics or R, however, is not an option for me. 

Cheers,
Alexander

**Comment by santsang** [comment]
Agreed.  We should appreciate others' effort in improving science including
developing educational software. It is hard to tell the timeline precisely
when it comes to invention. Sandro

**Comment by AlexanderLyNL** [comment]
This is a continued effort that we address on a daily basis.
