### ISSUE TITLE
Problem with 2x2 contingency table

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-desktop#1243]
[2x2CT.docx](https://github.com/jasp-stats/jasp-desktop/files/174503/2x2CT.docx)

**Comment by FransMeerhoff** [comment]
Dear Nikita,

Thanks that you manage to send us the proper data file.

In fact this issue is not a bug but a matter of correct formatting the data input file.
I've attached the corrected data input file CT2x2-new.txt that will give the right result for you.
(Latest version of JASP 0.7.5.5 will recognise .txt as .csv file)
The main difference with you're data file is that the first line is now interpreted as column info.
That's the reason why your 1 value disappeared and became 0.

After reading this attached file in JASP you select:  A->Rows, B->Columns, Count->Counts and you will find the proper result.

I hope that this information and data will solve your problem.

Kind regards
Frans Meerhoff

[R-2x2.txt](https://github.com/jasp-stats/jasp-desktop/files/184073/R-2x2.txt)

**Comment by FransMeerhoff** [comment]
Dear Nikita,

This is the file I was talking about in previous comment:  CT2x2-new.txt.
Difference between the other file i sent is that it contains "" and it was directly generated b R. 
[CT2x2-new.txt](https://github.com/jasp-stats/jasp-desktop/files/184083/CT2x2-new.txt)

Kind regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Dear Frans,

thank you. Now all is OK with BF for contingency tables. I missed the titles for rows and columns.

Всех благ,
НХ
