### ISSUE TITLE
Save as .zip option?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1250]
Since the .jasp format is really a .zip format, it should not be too much trouble to include the .zip format under the "save as" explicitly. I think many people will find this handy (they will immediately have all the figures at their disposal, without having to copy-paste each one), and if it just a relatively minor change I think we should do it.

**Comment by raviselker** [comment]
I disagree. It's better if the files inside the .jasp file stay hidden because I think normal users can get confused by what's inside of them (for example, the data is stored in binary format inside the .jasp files). However, we do want a way of extracting the data, results, and images from the .jasp file. A better way of doing this is by including the "export" function in the file tab to export data and results, and a "save as" option in the dropdown menu for the images.

**Comment by EJWagenmakers** [comment]
OK
