### ISSUE TITLE
Loglinear - frequentist and Bayes - more than one dataset

### ISSUE THREAD

**Issue by coledavis** [jasp-stats/jasp-desktop#1258]
These work if the file just has one dataset, e.g. V1, V2, V3, Count1.
However, if you have another dataset there, e.g. V1,V2,V3, Count1 and also NV1, NV2, NV3,Count2,
then Loglin will run one of the data sets but not the other one.

Frequentist Loglinear error message: 
Poisson GLM is undefined - the count variable X contains empty cell(s) or NaN.
Bayesian Loglinear error message:
Bayes Factor is undefined - incomplete contingency table, the count variable X contains empty cell(s) or NaN.

I attach 3 files. In the first two, the data sets work. In the third, the two data sets are together, and one does not work.
[test1.txt](https://github.com/jasp-stats/jasp-desktop/files/184753/test1.txt)

[test2.txt](https://github.com/jasp-stats/jasp-desktop/files/184754/test2.txt)
[test3.txt](https://github.com/jasp-stats/jasp-desktop/files/184755/test3.txt)

**Comment by FransMeerhoff** [comment]
Dear ColeDavis

The Log-Linear indeed does not work for for the combined dataset 3 where the two data sets are combined. That's because the combined dataset contains empty cells. 
If you look in the screen shoot below cells are empty and if the data has empty cell the log linear model does not run. The number of rows in both dataset should be equal with no empty cells.

![screen shot 2016-03-23 at 11 45 00](https://cloud.githubusercontent.com/assets/15656960/13982897/cd9e0e5c-f0ec-11e5-9a2a-94f45f316071.png)

Kind Regards
Frans Meerhoff

**Comment by coledavis** [comment]
Dear Frans,

I think you misunderstand the nature of the problem. The two data sets are not to be run together.
Using the third file, you either user the variables for one of them, or the variables from the other. 
But while each dataset works perfectly well in a separate file, one of them will not work if in the same file.
I hope that that clarifies the situation.

Kind regards,

Cole

Cole Davis

0208 458 8606 / 0791 8212 478  www.coledavis.org 


Date: Wed, 23 Mar 2016 03:48:47 -0700

**Comment by Tahiraj** [comment]
Hi Davis,
@coledavis when you combine the two dataset, in first dataset you have 18 rows and in second dataset you have 32 rows.  For this combined dataset, In JASP cells without data are considered as empty rows from 19-32 for first 4 columns, that is why you see the dot in those cells. In the current version of JASP for log-linear we do not have the option to delete the empty rows. So when you analyse by combining two dataset with unequal number of rows, log-Linear model take the cells from line 19 till 32 for dataset1 as empty and gave the error message. Whereas dataset 2 works perfectly well in the combined file. Also each dataset works perfectly well in a separate file because loglinear model consider 19 rows for dataset 1 and 32 row for dataset 2. 
I hope this clear the issue. If have further any query please let me know.

Best,
Tahira

**Comment by coledavis** [comment]
Hi Tahira

The two datasets should not be examined together.
What I meant is that if they are examined in the same file, separately, they do not both work. 
Please check the third file. First, choose the variables for one data set and see if it runs properly.
Then move the variables back and try the variables for the other data set. You will find that one data
set does not work.

I hope you understand now.

Kind regards,

Cole

Cole Davis

0208 458 8606 / 0791 8212 478  www.coledavis.org 


Date: Wed, 23 Mar 2016 06:10:04 -0700

**Comment by Tahiraj** [comment]
@coledavis please will you send me the screenshot of JASP for dataset of thirds file showing where it works and where it doesnot.
Best,
Tahira

**Comment by boutinb** [comment]
This issue is closed due to long inactivity.
