### ISSUE TITLE
Principle of marginality in classical rmANOVA?

### ISSUE THREAD

**Issue by ZuccheroZsuzsi** [jasp-stats/jasp-desktop#1279]
Hi!

Performing the Bayesian repeated measures ANOVA I noticed that the main effects are included in the interaction effects, which is, I think, according to the principle of marginality? 
However, in the classical (frequentist..) rmANOVA in JASP the output only gives main effects OR interaction effects; maybe offline the main effects ARE included in the interactions, but it is just shown in the output line (hence, the outputted "factor 1 * factor 2" is in fact "factor 1 + factor 2 + factor 1 * factor 2")? Or are the main effects not included in the interaction effects? (Comparable to SPSS??)

Thanks in advance!
Best,
Zsuzsi

**Comment by raviselker** [comment]
The classical rm ANOVA only fits one model (the full model, including main effects and interactions, if you do not specify this otherwise in the "model" menu). The ANOVA table you see in JASP lists the test of each term in this full model. 

The Bayesian rm ANOVA works a bit different. Here, all models are fit (unless you specify a certain term as nuisance in the "model" menu) and compared to each other. Therefore the output explicitly shows that the model includes the main effects and the interaction effect.
