### ISSUE TITLE
Pop-up when not connected to internet

### ISSUE THREAD

**Issue by raviselker** [jasp-stats/jasp-desktop#1357]
If you are not connected to the internet and open JASP the following window pops up:
<img width="403" alt="screen shot 2016-06-24 at 14 01 14" src="https://cloud.githubusercontent.com/assets/4669197/16363804/9c40962e-3bd6-11e6-9154-440ffb8b6a9a.png">

I think it's a bit annoying that a pop-up appears if you're not connected to the internet (you can use most functionality without having internet). Therefore I would get rid of this pop-up message.

**Comment by akashrajkn** [comment]
@raviselker , this does not happen on windows 10 (if you aren't connected to internet, and then you try to login to OSF in jasp, then this pop-up shows up - which is the intended behavior). 

Do you get this popup when you start jasp? And is this a mac-specific issue?

**Comment by raviselker** [comment]
Yes, I get this popup when I start jasp on osx. I haven't tried it on a different os so I don't know what happens there.

**Comment by boutinb** [comment]
Frans and me are already busy with this problem: when you have once used the OSF, and clicked on the 'remember me'checkbox, each time you start JASP, it tries to connect again to OSF. We want to change this behaviour. so that it tries to connect to OSF only when needed. This problem is related to the error when double-clicking JASP file on Mac
