### ISSUE TITLE
Importing .sav SPSS file truncates numeric variable at decimal

### ISSUE THREAD

**Issue by jackrsteiner** [jasp-stats/jasp-desktop#1364]
File>open>"*.sav" truncates numeric variable samples at decimal point. .sav file generated in SPSS, opens successfully with SPSS and PSPP. Same data opens without problem when saved as .csv.

[Sample.zip](https://github.com/jasp-stats/jasp-desktop/files/345657/Sample.zip)

**Comment by aknight1-uva** [comment]
Can't reproduce with newest (pre) release version. - Column 1 appears be an integer type, in column 2 I get to see fractional parts of floating point number where appropriate.
It if the issue is with column 1, then it's as designed - SAV import (currently) converts decimal columns with no rows containing a fractional part of the value to an integer.

**Comment by jackrsteiner** [comment]
Some more details:

- OS X 10.11.4
JASP Version 0.7.5.6
Built on: April 21 2016 (pre-built download)

- The issue is with column 2
Anticipated Value, JASP Import Value
4.2, 4
5.2, 5
5.63, 5
2.1, 2
1.6, 1
...

I'll gladly try the latest (pre) release version, but I'm having trouble with qmake right now.

**Comment by FransMeerhoff** [comment]
Hello @jackrsteiner 

The pre release version for JASP 0.8. Beta 1 is allready available for Mac OS at https://static.jasp-stats.org/JASP-0.8.256.0.dmg  
You can try this version and check if this will solve your problem.
We are planning to release a stable version on short-term.
And we are curious to hear your results.

Kind regards
Frans Meerhoff

**Comment by jackrsteiner** [comment]
Opens sample.sav file just fine. Thanks!
