### ISSUE TITLE
Bayes Factor 10 = 66 while frequentist ANOVA gives p =.159

### ISSUE THREAD

**Issue by Adam-1987** [jasp-stats/jasp-desktop#1386]
Hi I'm doing an experiment with repeated-measures 3x3 design.

I ran Bayesian Repeated Measures ANOVA in JASP and it gives me a BF10 for one independent variable (TMS regions) of 66 - indicating strong evidence for the alternative hypothesis.

However when I ran a frequentist repeated-measures ANOVA it gives a p-value of 0.159 of the main effect of TMS region on reaction time.

Does anyone knows why they disagree so much?

Thanks

![anova 1](https://cloud.githubusercontent.com/assets/20669327/17152597/5e8a6100-5370-11e6-91fa-aaf822e38804.png)
![anova 2](https://cloud.githubusercontent.com/assets/20669327/17152598/5e8d1f8a-5370-11e6-8af0-e70c08d20354.png)

**Comment by Suggestions-Only** [comment]
I can't really be sure, but I'm going to assume this isn't some kind of program code error.  I think it's because if you include a bunch of variables in a linear regression model, they eat up each other's explanatory variance.  But the Bayesian version evaluates each variable on its own, as well as the possible combinations.  What does your analysis look like if you only include TMS Region?

**Comment by Adam-1987** [comment]
Hi,

Sorry I got a bit confused - did you mean that I should use the variable (Congruency) other than TMS Region (2 independent variables in all, each has 3 levels)  as a nuisance in the Bayes repeated-measures ANOVA?

If so then I just tried it - now the BF10 is even larger, it's 78 now :/

**Comment by Suggestions-Only** [comment]
No, I meant rerun the ANOVA with TMS Region as the only independent variable and see if that makes your p-value smaller.
