### ISSUE TITLE
Error when adding ordinal or nominal variables

### ISSUE THREAD

**Issue by RandiLGarcia** [jasp-stats/jasp-desktop#1390]
Hi, I just downloaded JASP today, version 0.7.5.6. I'm running Windows 10. Whenever I add an ordinal or nominal variable (I tried in descriptives and ANOVA) it gives this error: 
"This analysis terminated unexpectedly. Please contact its author.\n\nError : map::at\n"

[JASPerror.zip](https://github.com/jasp-stats/jasp-desktop/files/387240/JASPerror.zip)

**Comment by FransMeerhoff** [comment]
Hi @RandiLGarcia 

This problem comes from the data file used.
A simple work around for this problem is. Exporting the data file as a .csv from JASP. Open this exported data file in JASP again and rerun the analyses. Then no errors occur.

Can you please send us the original data file you use. Then we can try to solve this problem.

Kind regards 
Frans Meerhoff

**Comment by RandiLGarcia** [comment]
Hi Frans,

I did not try it yet, but thanks! Here is the original .sav file.  I tried several SPSS files and the same error occurs for all (that I tried). It seems to recognize the categorical variables as categorical, but cannot work with them from .sav files.

Thanks again,
Randi

**Comment by boutinb** [comment]
The SPSS file was not yet officially supported. Now it is. Do you have still this problem in the newest version of JASP (0.8.1)?

**Comment by boutinb** [comment]
If this problem comes up again with the newest version of JASP, reopen this issue.
