### ISSUE TITLE
[Linux packaging] R Dependencies

### ISSUE THREAD

**Issue by stephensrmmartin** [jasp-stats/jasp-desktop#1475]
I maintain the arch linux AUR build of jasp, and I think it's time for a repackaging.

Currently, I package both jasp and a jasp-rbundle.
The jasp-rbundle provides all JASP r deps recursively (so dependencies of jasp R package dependencies).
For jasp to work, I had to let this install to the R system library, and specify that the rbundle provides r-cran-\* (where \* is every single R package ever needed for JASP).

The problem with this, is that if an arch user wants to install a separate r-cran-\* package, it will conflict. 

Ideally, I would want to install all of JASP's R dependencies to the JASP directory, and JASP should load an R session that looks in the system library _and_ in a jasp directory (perhaps relative to the binary).
Is there any way to do this, so that installing JASP doesn't touch R's installation?

**Comment by akashrajkn** [comment]
I modified enginesync.cpp (lines near 347) to point to the path where R packages are installed. This worked on mac. Can you try specifying the rHomePath and check if it works?

**Comment by stephensrmmartin** [comment]
Will this permit JASP to use packages from *both* the R system library and a custom directory?
That is-- I want JASP's r session to find packages in /usr/lib/R/library/ and /usr/share/JASP/R/library or something.
That way, R's standard install can be used, but JASP's package dependencies can be put in the latter directory.

**Comment by akashrajkn** [comment]
I will have to check that. I haven't tried specifying multiple paths for packages.

**Comment by akashrajkn** [comment]
@stephensrmmartin , in enginesync.cpp line 411 (under linux macro), you can specify the R_LIBS path. You can add multiple paths for R packages here. I tested this on ubuntu 15.10. Hope it helps

**Comment by stephensrmmartin** [comment]
I'll look into this later.

Seems like this should be a compile-time option rather than a per-distro patch.

**Comment by stephensrmmartin** [comment]
This worked! I was able to push all JASP R packages to the JASP directory, with the exception of RInside which I could package by itself if need be.

The only remaining issue I have now is that the .desktop you all ship use custom categories, so it doesn't show up in the XDG standard directories. A bit silly, imo, but I could either add a .menu file or change the category --- I'm opting for the latter.
Also, .jasp files don't seem to be associated with jasp, even though I updated the desktop and mime databases.

**Comment by FransMeerhoff** [comment]
Hi Akash,

Hello, I still hope you’re OK.
I’m very curious about the this issue too, because we still have a problem on Ubuntu too regarding this subject.

I’m looking for a solution ta add one big ASP R-package,  or at least a minimals set of R-packages, to the ppa, and after installation of JASP refer with the R_LIBS environment  to this and not to the system libraries of R.

We are still aware  that when we  deliver the next release on Ubuntu, this will not be ideal,  because of problems with adding some specific R packages to the ppa, e.g.  qgraph, org GPArotation.

Do you think that is possible ?

Cheers Frans


On 21 Sep 2016, at 19:59, akash raj <notifications@github.com<mailto:notifications@github.com>> wrote:


I modified enginesync.cpp (lines near 347) to point to the path where R packages are installed. This worked on mac. Can you try specifying the rHomePath and check if it works?

**Comment by mih** [comment]
I would be interested in what you think about the patch linked in gh-1473. This makes JASP use user-installed R packages. With this I can pull any dependency from CRAN that I desire (as a user) without having to go through an admin.

**Comment by mih** [comment]
Actually, JASP could do that by itself and on-demand. Whenever some package is not there, it could obtain it from CRAN.

**Comment by stephensrmmartin** [comment]
I don't like the idea, personally. It seems like an awfully 'windowsy'
solution to require each user to install needed dependencies. It's a
waste of space. A better solution is to build all non-standard JASP R
dependencies (recursively) into a library that JASP uses (thus doesn't
conflict with any user or system packages), and thus all users benefit from.

It seems odd to use user libraries for the jasp dependencies. That would
mean 1) duplicate libraries 2) JASP may work for one user and not for
another.

**Comment by mih** [comment]
This is not about "require each user to install needed dependencies". This is about being able, at all, to use user-libs when the system doesn't have them. Many reasons will make such a solution useful. In Debian, we face the situation that we won't have afex because of a stupid licensing issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800891

I can make users wait for a resolution, or let them install it via R.

Moreover, in the past ten years the absolute #1 complaint I got as a package maintainer was "my admin won't install the dependencies".

That being said, I agree 100% that system packages are better. But you won't get a recursively compiled blobs of lots of CRAN packages into a distribution like Debian.

**Comment by AlexanderLyNL** [comment]
See flatpack 

https://jasp-stats.org/linux-installation-guide/
