### ISSUE TITLE
The first t-test takes pretty long

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#1546]
When I compute a Bayesian t-test, the first analysis takes pretty long. After that's done, the robustness check and sensitivity analyses are pretty quick. @quentingronau, any clue as to why this happens? 
E.J.

**Comment by quentingronau** [comment]
Hi @EJWagenmakers ,

I am not completely sure. It could be the case that this is due to the state system which saves results and prevents them from being recomputed unless this is necessary, but this depends on what exactly changes from one analysis to the next. If you are sure that, e.g., the second analysis cannot be retrieved from the state object and is still taking less time than the first, this might be a question for the programmers.

Cheers,
Quentin
