### ISSUE TITLE
Wrong code for calculating (repeated) contrasts?

### ISSUE THREAD

**Issue by Kim-White** [jasp-stats/jasp-desktop#1557]
I use version 0.8.0.0. When analyzing my data (rep. meas. ANOVA) I was surprised by the p-value of the contrasts. When calculating the same with a t-test and in SPSS I get a different value. The t-test in JASP and the rep. contrast  in SPSS do generate the same p-value. Wrong code?

Thanks!

![jasp_rep_contrast](https://cloud.githubusercontent.com/assets/23704027/20569493/8dba38c2-b1a0-11e6-9575-0cf383221ecf.jpg)

**Comment by FransMeerhoff** [comment]
@Kim-White 

Thanks for finding and reporting this issue but
Sorry for the late reaction. I've forwarded it to the associated developer.

@JohnnyDoorn 

Can you please take a look at this ?

Kind regards
Frans Meerhoff

**Comment by JohnnyDoorn** [comment]
@Kim-White 
Hi Kim,
Thanks for letting us know - I am currently looking into the dissimilar results. If possible, could you please send me your dataset? This way I can try to reproduce the problem to get a better understanding of what is going on in both programs. As a sidenote, the repeated measures ANOVA with contrasts should not necessarily yield the same results as a single paired samples t-test (e.g., because of the contrast corrections - are they specified similarly in both SPSS and Jasp?). 
Kind regards,
Johnny
