### ISSUE TITLE
Cannot re-add model component (bug?)

### ISSUE THREAD

**Issue by nronaldvdberg** [jasp-stats/jasp-desktop#1711]
## Environment (for bugs)

* JASP version: 0.8.1.1.
* OS name and version: Windows 10
* Analysis:
When i do a two-way ANOVA, open the "Model" tab, and then remove the interaction term from the model, it cannot be re-added. I guess this is a bug. See video for a demonstration of what i mean.
[Jasp_bug.zip](https://github.com/jasp-stats/jasp-desktop/files/888344/Jasp_bug.zip)

**Comment by UppsalaCognitionLab** [comment]
Well, the interaction term appears as a component in the right-hand text box. To me, it would be most natural that after i click the "left-ward" triangle button, the term moves from right-hand box to the left-hand box, consistent with what usually happens when pressing that button? It's no big deal to me, as i will never need this functionality, but it just felt a bit odd that something disappears when you expect that it will only move from one box to another.

**Comment by boutinb** [comment]
The problem is that if you have a lot of factors, and the list may grow exponentially. That's why the list on the left side is called Components: only the factors are here listed. I'll add a tooltip to make it clearer how to make interaction. We will also update the Help.
