### ISSUE TITLE
Independent Samples T Test SE Difference Bug?

### ISSUE THREAD

**Issue by JASPUser** [jasp-stats/jasp-desktop#1734]
## Environment (for bugs)

* JASP version: 0.8.1.1
* OS name and version: Win 7 64 bit
* Analysis: 
Testing for differences in Hair index against Diet type.  Hair.Ind against Diet
![image](https://cloud.githubusercontent.com/assets/27625429/25071508/47371e14-22fd-11e7-9ab1-99b2b456f422.png)
This should be easy to explain or fix: **SE Difference** is reported the same value for Student's and Welch's. 
In theory, the SE for each of these tests is computed differently. 
Note: The reported confidence intervals for Student's and Welch's both appear correct, so this implies Student's SE is getting computed somewhere in the code, it's just not getting reported where it should.

Also this implies a different Cohen's D.  
Note: Student's Cohen's D appears correct(!)   **Cohen's D for Welch's** should be 0.7646 ?

[Bed Bugs.txt](https://github.com/jasp-stats/jasp-desktop/files/924314/Bed.Bugs.txt)

1  Pooled S should be used for Student's SE Difference  (SE=20.1461)  Cohen's D for Welch's should be 0.7646
2 Fix SE Difference value for Student's t  and Cohen's D for Welch's 

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by JohnnyDoorn** [comment]
Hi,
Thanks a lot for pointing out this inconsistency. I have just fixed it and it will be in the new JASP release. One small question though - are you sure the Welch's Cohen's d should be 0.7646? I ran your bed bugs data (testing hair.ind ~ diet) through both the updated JASP and R (lsr package), and it gives me a Cohen's d of 0.695 (so different from Student's Cohen's d, but also from your calculation). How did you calculate it? 
Here's my code:
```{r}
sdPooled <- sqrt(((sd1^2)+(sd2^2))/2)
d <- (m1 - m2) / sdPooled
```
where m1 and sd1 correspond to one group, m2 and sd2 to the other. 
Again, thanks for your input!
Johnny

**Comment by JASPUser** [comment]
Hi Johnny,

thanks.


No I am not sure how to calculate Cohen's d for Welch's.  I used the SPSS output and my HP 10bII+ calculator to check JASP:

[cid:f2969329-a07d-49cf-85e4-2e12c28a78eb]

and

 [cid:2ba797ce-ebf5-41ca-bac5-dc1a963700d9]

which is the formula I use for the Two independent samples Student's t.


I used the SPSS output, checking both forms of the formula above that use the observed t and the difference of means and se, for the Welch's test version of Cohen's d and they both give the d= 0.7646 value. I also did this in R manually, using the imported data. I used the same formula simply on the basis that Welch's computes its own value of se, assuming independent samples, and that the observed t given by SPSS uses Satterthwaite's approximation for df, as the adjustment.


But I now see your pooled estimate of s for Welch's, and the discussion on https://stats.stackexchange.com/questions/210352/do-cohens-d-and-hedges-g-apply-to-the-welch-t-test

[https://cdn.sstatic.net/Sites/stats/img/apple-touch-icon@2.png?v=344f57aa10cc]<https://stats.stackexchange.com/questions/210352/do-cohens-d-and-hedges-g-apply-to-the-welch-t-test>

Do Cohen's d and Hedges' g apply to the Welch t-test?<https://stats.stackexchange.com/questions/210352/do-cohens-d-and-hedges-g-apply-to-the-welch-t-test>
stats.stackexchange.com
How do you go about calculating effect size for the Welch t-test?


I also tried lsr and effsize libraries in R .

CohensD in lsr didn't work for me and effsize cohen.d gives d= 0.7672357 for pooled=T (i.e Student's?)  which just seems wrong.



BTW

JASP doesn't seem to have an equivalent to SELECT CASES or subsetting the response based on a category level.  This would be nice.

Do you want to enter it as a job or shall I?


I also have a proposal for a simple version of Population Proportions tests and intervals for one and two samples like prop.test (or binomial test) but where the user just enters the simple counts for x and n and the package computes either a test p-value or Wald confidence intervals and estimates

rather than working from raw data.  So this is just a simple dialogue with no data to import.

I have 4 R scripts for this task, which we use in the First Year Stats course.

I also have an extra script which calculates the required sample size for a given confidence level.


sincerely, Peter



________________________________

**Comment by JohnnyDoorn** [comment]
Hi Peter,
Thanks a lot for your elaborate response! I took a look at the effsize package, and saw that it indeed produces different results for effect sizes than the lsr package. 
Here is the R-code I used to compare the two:
```{r}
dat <- read.csv("/home/johnny/Downloads/BedBugs.csv")
require(lsr)
require(effsize)

g1 <- dat$Hair.Ind[dat$Diet == 0]
g2 <- dat$Hair.Ind[dat$Diet == 1]
meandiff <- mean(g1) - mean(g2)

cohensD(dat$Hair.Ind ~ as.factor(dat$Diet), method = "pooled")
cohensD(g1, g2, method = "pooled") ## These two produce the same result, so either a formula can be specified, or the data for two groups (g1, g2)

cohen.d(dat$Hair.Ind ~ as.factor(dat$Diet), pooled = T, paired=F) 
cohen.d(g1, g2, pooled = T, paired = F) # effsize package appears to be doing different things based on how the function is called

cohensD(dat$Hair.Ind ~ as.factor(dat$Diet), method = "unequal") 
cohensD(g1, g2, method = "unequal")  ## Same as before, but now without using the pooled variance, but the average (specified by method = "unequal")

cohen.d(dat$Hair.Ind ~ as.factor(dat$Diet), pooled = F, paired = F) # This gives Glasses delta, which uses the standard deviation of the control group, or:
meandiff / sd(g1) # or, depending on how the function is called:
meandiff / sd(g2)
 ```
In summary, we have chosen to adapt the way Welch's Cohen's d is calculated in the lsr package (so indeed the Bonnett way, as explained in your CrossValidated link). I think it's neatly straightforward in how it's calculated and it feels less biased than using only one of the two standard deviations available. However, in all the different ways, I have not been able to reproduce the result SPSS gives, and I can't find any documentation on how they calculate it, which is a shame. 

As for selecting cases to be analyzed, instead of the full dataset, we are currently working on this and it should be implemented either in the next release or the one after (within a couple of months)! I fully agree that it's a crucial feature.

If you want to do a statistical test without inputting the raw data, I would like to refer you to the summary stats module in JASP (click the icon in the upper right corner, then go to 'Modules', then enable the summary stats module. This adds a new tab to the program, where you can select different tests (e.g., binomial, t-test, correlation). There, you can input only the test statistic, and get some analytic output based on that. For the binomial tests, you can just enter the number of successes and failures, in order to get a table and plots with (Bayesian) results - see also the attached screenshot. Frequentist results are not available for this, however.
![jaspsumstatsbinom](https://cloud.githubusercontent.com/assets/15704203/25229168/92d94606-25cf-11e7-9562-4abd3b7e252e.png)

I hope this answers your queries!
Kind regards,
Johnny
