### ISSUE TITLE
False Descriptives in Bayesian t-Test

### ISSUE THREAD

**Issue by SurpriseIce** [jasp-stats/jasp-desktop#1766]
## Environment (for bugs)
* JASP version: 0.8.0.1
* OS name and version: MAC OS Yosemite 10.10.5
* Analysis: Bayesian Independent Samples t-Test 

Hey everyone,
at first, let me thank you for this great tool! 
In my analyses, I came across some strange calculations: In the bayesian independent samples t-test, I had a look on the descriptives of my data. The considered variables are error rates ranging from 0 to 1. However, the descriptives gave means ranging from 11 to 37. Same for standard deviations and errors. Interestingly, those descriptives are not the 'real' means, SD and SE (as computed by R) multiplied by 10 or 100, but rather differ in a more complex fashion.
You find the sav-file in the attachment.

Best regards
Alex

[Archiv.zip](https://github.com/jasp-stats/jasp-desktop/files/987682/Archiv.zip)

**Comment by boutinb** [comment]
@SurpriseIce There seems to have a problem when loading the data from SPSS. When I do this.it tells me that the columns x.. are nominal text column, it should be scale columns.
There is a workaround: just after loading the sav file, change the columns as scale columns by clicking the column icon. Then you can add your analysis.
I'll check further to understand why the columns are considered as strings.

**Comment by boutinb** [comment]
@SurpriseIce I see that in your SPSS file, the Measure of the columns are set to Nominal. That's why JASP reads them as nominal text. 
What is strange in your JASP file, is that the columns are set as Nominal Integer values. I cannot reproduce this: if I read the data from JASP, is sets it as Nominal Text (you see the 3 balls with a kind of @ sign in it). Your JASP file shows the columns as Nominal Integer (3 balls without sign in it), which is completely wrong, and that's  why you get wrong results.
Do you know how you got this situation? If you read again the SAV file, do you get the tight column types in JASP?

**Comment by SurpriseIce** [comment]
Well, I see. Thank you very much. Honestly, I don't know how this messed up. Maybe because I mixed up R and SPSS in my analysis and handled the file not thoughtful enough. However, now I can use JASP for my analysis that is a great help compared to bayesian analysis in R.
Thanks again!
