### ISSUE TITLE
Program reads "analysis terminated unexpectedly"

### ISSUE THREAD

**Issue by lynnalk** [jasp-stats/jasp-desktop#1797]
## Environment (for bugs)

* JASP version: 0.7.5.6
* OS name and version: Yosemite, version 10.10.5
* Analysis: Correlation Matrix
## Environment (for enhancement requests)
 
* Enhancement: program won't recognize certain data in simple correlation matrices-- says "unknown error"
* Purpose: 

<img width="645" alt="screen shot 2017-05-31 at 11 27 28 am" src="https://cloud.githubusercontent.com/assets/29101170/26679590/cc84b60c-46a3-11e7-9586-7bfa1c7b3893.png">

**Comment by TimKDJ** [comment]
Hi @lynnalk,

It appears that you are using a rather old version of JASP.
The issue you're experiencing is quite possibly already fixed in a more recent version.
Could you install the latest version from [our website](https://jasp-stats.org/download/) and see if the problem persists? If so, could you give us steps to reproduce the problem?

Thanks!

**Comment by boutinb** [comment]
If this error still occurs, re-open this issue.
