### ISSUE TITLE
repeated measures ANOVA -> analysis terminated unexpectedly

### ISSUE THREAD

**Issue by Goalie26** [jasp-stats/jasp-desktop#1824]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Sierra 10.12.5
* Analysis: repeated measures ANOVA
![bug report jasp](https://user-images.githubusercontent.com/29537058/27278538-fb878c3a-54e1-11e7-8368-6b9eea8ce53e.jpeg)

## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by JohnnyDoorn** [comment]
Hi,
Would you feel comfortable sharing your dataset with us? This way we can try to replicate your issue, because unfortunately the error message is not very informative. A dataset with only the three columns you specified in you RM ANOVA model would also work. 
Thanks for your report!
Johnny

**Comment by Goalie26** [comment]
Hi Johnny,

of course I am. Please find it attached.



Chris

**Comment by JohnnyDoorn** [comment]
Hi Chris,
I did not get the email with the notification, and I cant find your attachment here - would you mind sending it again? Or you can directly email me at j.b.vandoorn [at] uva.com
Kind regards,
Johnny

**Comment by Goalie26** [comment]
Hey Johnny,
for whatever reason this does not work with the email you gave me either. ...and I know now why I did not work with my first try: file type is not supported ;-) as it is a .csv
Therefore, your getting it as a .zip, now.

[Auswertung.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/1085481/Auswertung.csv.zip)

Kind regards, Chris

**Comment by JohnnyDoorn** [comment]
Hi Chris,
Thanks for sharing - I just tried to do what you were doing, and for me it was working fine - please see the attached .jasp file (in a zip file). My colleague tried the same and it worked for him too (he is on the same mac os as you are). What we did was specify the RM model with 1 factor with 3 levels (kommando). I see in the background of your screenshot that you added an interaction between kommando and kommando, which seems strange. How did you specify your model, because maybe that interaction was the thing that causes some problems..
[ChrisRMANOVAjasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1085540/ChrisRMANOVAjasp.zip)

Kind regards
Johnny

**Comment by Goalie26** [comment]
Hi Johnny,
I have just checked. Now everything is working totally fine. I guess you are right: It was my mistake "wanting" an interaction between command and command...
Thank you for your help and keep up the great work. I have only started using JASP (recommended by a friend in psychology) and I simply love it! ... and the best is: my students do too.
Kind regards
Chris
