### ISSUE TITLE
Will not open at all

### ISSUE THREAD

**Issue by ArthurStone** [jasp-stats/jasp-desktop#1863]
Using Mac OS 11.10.2 and it errors out before opening.
![image](https://user-images.githubusercontent.com/30378233/28494845-873b3084-6eef-11e7-8219-076014334c8e.png)

**Comment by boutinb** [comment]
@ArthurStone I can see from the error that there is a problem when trying to create the temporary folder. Apparently this is due to permission problem. Is it possible to open a terminal, and to to type this:
   cd ~  //This is to go to your home folder
Then
  ls -al  // This is to list all your subfolders
If you do not see a '.JASP' folder here (with a '.' before JASP), then type this
  mkdir .JASP     // Don't forget the '.' before JASP!
Then Type
  chmod 777 .JASP // This gives all permissions to everybody.
Then go to the .JASP subfolder:
  cd .JASP
And then create the temp subfolder
  mkdir temp
Again give all permissions:
  chmod 777 temp

Then start JASP again.

**Comment by ArthurStone** [comment]
Thanks.
However, it says “permission denied” when I issue the mkdir command.

----------------------------------------------------------
Arthur A. Stone, Ph.D.
Professor, Department of Psychology
Director, USC Center for Self-Report Science
University of Southern California
Suite 405, 635 Downey Way
Los Angeles, CA  90089-3332
O: 213 821-1781  C: 631 682-0014
---------------------------------------------------------

**Comment by ArthurStone** [comment]
Thanks.
However, give error “No permission” when I issue the mkdir command

----------------------------------------------------------
Arthur A. Stone, Ph.D.
Professor, Department of Psychology
Director, USC Center for Self-Report Science
University of Southern California
Suite 405, 635 Downey Way
Los Angeles, CA  90089-3332
O: 213 821-1781  C: 631 682-0014
---------------------------------------------------------

**Comment by akashrajkn** [comment]
@ArthurStone use `sudo mkdir .JASP`

**Comment by boutinb** [comment]
@ArthurStone You use a user who is not admin of your mac. The sudo command will ask for an admin user.
Would it be possible to log in on your mac directly with an admin user?

**Comment by boutinb** [comment]
No answer after 5 months, so this issue can be closed. This can be re-opened if necessary.
