### ISSUE TITLE
Spearman and Kendall's Tau confidence intervals

### ISSUE THREAD

**Issue by tressoldi** [jasp-stats/jasp-desktop#1874]
## Environment (for bugs)

* JASP version: 8.1.2
* OS name and version: Windows 10
* Analysis: Correlation
## Environment (for enhancement requests)
 
* Enhancement: Contrary tot the Pearson correlation, I don't see the confidence intervals of the Spearman and Kendall's Tau
* Purpose: Is it possible to add CIs to these stats?

**Comment by EJWagenmakers** [comment]
You are right! We ought to fix that. Let me ask @JohnnyDoorn or @vandenman to take a look at this. 
Cheers,
E.J.

**Comment by lindeloev** [comment]
When you do, make the settings- and results layout consistent with the Bayesian analysis. 

Settings: I have a slight preference for the radio button (select one) over the tick boxes (select multiple); mostly because tick boxes allow for selecting zero. IF multiple tick boxes, then perhaps one table per correlation type rather than everything in one table (?) - or the choice.

**Comment by AlexanderLyNL** [comment]
Added this on the 7th of September
