### ISSUE TITLE
Install on Debian 9

### ISSUE THREAD

**Issue by cogneurotrololo** [jasp-stats/jasp-desktop#1888]
Hi there, 

First of all, thanks for this great software, I absolutely love it!

However, I am having a really hard time compiling JASP on some machines running Debian 9 as already documented by other people running previous Debian releases https://github.com/jasp-stats/jasp-desktop/issues/1146 https://github.com/jasp-stats/jasp-desktop/issues/764

Given the importance of Debian in the Linux world, do you plan to make JASP available on Debian similarly to what done for Ubuntu (e.g., without having to build it from source and run in all sort of problems)? I think a lot of people would benefit from it. I asked this on the twitter page and the answer was "We are working to make this process easier. If you want the details feel free to contact the programmers through our GitHub page", so please I would like to know more about it.
Thanks!

**Comment by FransMeerhoff** [comment]
Hi @cogneurotrololo 

Thanks for your nice words about JASP.
This issue is indeed not new for us but is still on our list to handle.
You will understand that making JASP available on a extra platform is a big effort,
but we do not underestimate the importance as you mention. 
For the moment please refer to Michael Hanke, see https://github.com/jasp-stats/jasp-desktop/pull/1471 , someone from the distro community who creates binary packages for Debian.
At that some point we will definitely have a solution to make this process easier, but unfortunately not yet.

Kind regards 
Frans Meerhoff
