### ISSUE TITLE
Repeated Measures ANOVA issues

### ISSUE THREAD

**Issue by janeller555** [jasp-stats/jasp-desktop#1909]
## Environment (for bugs)

* JASP version: 0.8.1.2
* OS name and version: Mac OS Sierra 10.12.6
* Analysis: Repeated Measures ANOVA
<img width="686" alt="screen shot 2017-08-10 at 9 57 33 pm" src="https://user-images.githubusercontent.com/30911419/29191973-7ca5fef6-7e17-11e7-9d85-ce08b392c6a0.png">

Help. 
## Environment (for enhancement requests)
 
* Enhancement:
* Purpose:

**Comment by TimKDJ** [comment]
Did you happen to name one of your RM factors the same as one of your between-subject factors?
The reason I ask is because your stacktrace is identical to the one reported in issue #1906.

If this is not the case, could you please provide us with a .jasp file (zip it and attach it to this post), so we have a better idea of what is going on?

**Comment by boutinb** [comment]
No response. If this error still occurs, re-open it.
