### ISSUE TITLE
B Correlation Matrix - UI needs some modifications

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#202]
- Drop the correlation coefficients option (only pearson is supported)
- Change hypothesis options to be, ρ ≠ 0, ρ > 0, ρ < 0
- Change 'Report significance' to 'Report supported correlations'
- Change 'Flag significant correlations' to 'Flag supported correlations'
- Add 'beta* prior width' options

**Comment by jonathon-love** [comment]
Woops, 'Report significance' should be 'Report Bayes factors', should be checked by default

**Comment by jonathon-love** [comment]
@AlexanderLyNL, could have take a look at these and see if i've forgotten anything?

**Comment by jonathon-love** [comment]
'beta* prior width' should be 'Beta* prior width', and should be hidden (or pink when in debug)

**Comment by jonathon-love** [comment]
So for the hypothesis for correlation, we can have the options:
- ρ ≠ 0
- ρ > 0
- ρ < 0

this is appropriate for pearson and spearman, because they both refer to the population value by ρ, however kendall uses τ. so i'm thinking we use ρ anyway, but we could also go for the options:

- Correlated
- Correlated positively
- Correlated negatively

@EJWagenmakers, do you have feelings either way?

**Comment by EJWagenmakers** [comment]
I'm leaning towards the verbal description: it is more clear and more
consistent with the description of order-constraints in the t-test.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
Let’s do

Population correlation ≠ 0 
Population correlation > 0 
Population correlation < 0 

then

**Comment by jonathon-love** [comment]
kinda long, i think i'm backing:
- Correlated
- Correlated positively
- Correlated negatively

**Comment by EJWagenmakers** [comment]
I agree with Jonathon: I don't like the term "population" because it has a
classical connotation. I can estimate rho sensible even when there is no
population. I just have a data-generating model with rho in it; you can
call "data-generating model" the "population", but that isn't always
appropriate.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
