### ISSUE TITLE
Cannot find charactor set wIndows-1254

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [jasp-stats/jasp-desktop#2051]
## Template for bug reports

I have a *.sav file opened with PSPP and SPSS. when I open it with JASP, following error occure.
"Cannot find charactor set wIndows-1254"

* JASP version:0.8.3
* OS name and version:PisiLinux 2.0
* Steps to reproduce: Open a *.sav file

**Comment by FransMeerhoff** [comment]
Hi @ayhanyalcinsoy 

Thanks for reporting this.
Could you send us an example file where this problem occurs?
(You can zip it and drag it to this issue)
Do you know if this file was built on a windows machine and later used on PisiLinux?

Cheers
Frans Meerhoff

**Comment by ayhanyalcinsoy** [comment]
[sessizlik.sav.tar.gz](https://github.com/jasp-stats/jasp-desktop/files/1398407/sessizlik.sav.tar.gz)

**Comment by boutinb** [comment]
This is solved in the new version 0.8.5

**Comment by ayhanyalcinsoy** [comment]
This issue goes on 0.8.5 with *.sav file. I saved it as *.csv file then jasp open it without error.

**Comment by JorisGoosen** [comment]
Are you sure you are using 0.8.5? Because when I try to open your .sav it opens it without a problem.
Maybe you can check in the right top of JASP? (See screenshot)

![schermafbeelding 2018-01-05 om 11 55 33](https://user-images.githubusercontent.com/29062713/34606385-655ccae2-f20f-11e7-8faf-c76e21b75b12.png)
