### ISSUE TITLE
Enhancement Request: Add the ability to “Split” analyses by a variable to every module or test

### ISSUE THREAD

**Issue by wjames35** [jasp-stats/jasp-desktop#2141]
Enhancement: Add the ability to “Split” analyses by a variable to every module or test
Purpose: Presently in JASP there is a field entitled “Split” under “Descriptives.” Please add this to every module! That would be huge. For instance, when I am teaching ANOVA, if there is a significant interaction effect, then this split feature would help me show students how to make sense of the significant interaction by testing the relevant slices (e.g., if there was a significant Therapy Treatment X Sex interaction effect, then you could then use the split function to do a follow-up ANOVA looking at treatment effects among males and treatment effects among females, thereby making sense of the significant interaction effect).

**Comment by lindeloev** [comment]
A few ideas to elaborate on this:

1. Sometimes people want to **"split by column"**, e.g. run t-tests on three columns. This would be quite typical for questionnaire data; say if it computes to two or three main indices. So a "split by" function could include the option to select by "Variable value" (select a single variable) or "Variable column" (select multiple variables). Hence the function may more adequately be described as an "Apply to" function. This would be an improvement over SPSS. Applying to multiple columns in SPSS would typically be done using syntax, and if this could be GUI, that would be awesome.

2. Under each analysis, there could be a section called **"Data handling"** or similar. See next point :-) 

3. "Data handling" would also include a **"Select Cases"** function, i.e. electing only rows that meet a specific criterion for that analysis. This would differ from SPSS where select cases is a background setting that affects all analyses from that point forward. I like the analysis-by-analysis select cases since that would be more transparent and reproducible. There is one potential downside to this: if people want to run multiple analyses using a particular select-cases setting they have to do "select cases" for each analysis.

I know that select cases will probably be important for my supervision of student projects in the spring (from March, approximately). It would be cumbersome to do in Excel.

**Comment by lindeloev** [comment]
I just saw #1934 which could also be an option under a "Data handling" section; though not sure. It's the same discussion about "data wide" versus analysis-specific options so just wanted to bring it up.

**Comment by AlexanderLyNL** [comment]
Thanks for the suggestions, this is something that we'll look into. Until we've implemented this, I can recommend the workarounds via Excel. Here are two gifs in which I explain how some of these things can be done: 

https://twitter.com/AlexanderLyNL/status/918197338841190400
https://twitter.com/AlexanderLyNL/status/918195429652750337

**Comment by AlexanderLyNL** [comment]
Can be done with filtering

https://jasp-stats.org/download/

**Comment by AlexanderLyNL** [comment]
https://jasp-stats.org/2018/06/27/how-to-filter-your-data-in-jasp/
