### ISSUE TITLE
B T-Tests, fix overlap of labels for credible interval

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#225]
hey quentin,

do you think we can get this in for the 0.6?

![screen shot 2015-01-29 at 11 04 03 am](https://cloud.githubusercontent.com/assets/3240247/5955843/82e46cec-a7a7-11e4-85e8-7afc7219b315.png)

**Comment by jonathon-love** [comment]
@EJWagenmakers, you had a couple of suggestions for this.

**Comment by quentingronau** [comment]
I will try. I have an idea for the credible interval values. Because it was important for Tahira, I will try to leave them at the coordinates where they actually are. But I can change the plot so that the text for the lower bound ends at its coordinate and the text for the upper bound starts at its coordinate, hopefully that will solve the issue. For the 95% symbol I will propably need to come up with some heuristic that automatically decreases its size. I will be at the office in the afternoon to work on it.
