### ISSUE TITLE
Unable to plot network graph when non-ascii character in filename

### ISSUE THREAD

**Issue by eisensafran** [jasp-stats/jasp-desktop#2252]
## Unable to plot network graph when non-ascii character in filename

* JASP version: 0.8.5.1
* OS name and version: Windows 10 , 1709
* Analysis: There is a error message that occurs every time I want to plot a network graph: 

> Error in grDevices::png(filename = tempFileName): kann png()-Ger�t nicht starten
(The last part is German and translates to: "Unable to find png() engine.)
* Steps to reproduce: 
Since Windows assigns the root folder to the user's name there are often cases where non-ascii characters are in the document's path (Example in my case: the German "ß"). There seems to be a problem with R's syntax that has issues with that case: [example](https://stackoverflow.com/questions/14093834/unable-to-open-png-device-in-loop)

**Comment by boutinb** [comment]
This problem was solved for most of the analyses by setting the working directory to the user temp folder, but unfortunately the network module uses special code that bypasses this fix. This will be solved in the next release.
For the time being, you can use this zip file
[JASP.zip](https://github.com/jasp-stats/jasp-desktop/files/1606549/JASP.zip)
It contains the R code for JASP with the fix for the network module. It must be set in your JASP installation folder, subfolder R/library. Here you have a JASP subfolder. Rename it, and unzip the JASP zip file attached.
Tell me is this works.

**Comment by eisensafran** [comment]
Hey boutinb! Yes, the code in the ZIP file you provided works just fine! 
Thank you for your quick response and let me know if you need some beta-testers!
