### ISSUE TITLE
Missing ability to edit data and variables directly.

### ISSUE THREAD

**Issue by PhilJdal** [jasp-stats/jasp-desktop#2268]
## Template for bug reports

* JASP version:
* OS name and version:
* Analysis:
* Steps to reproduce: 

## Template for enhancement requests
 
* Enhancement:
* Purpose:

**Comment by EJWagenmakers** [comment]
Duly noted. We plan to add some editing facilities in the near future (the kind of stuff that is unpleasant in Excel/Libre Office), but for now we believe most users would prefer us to include other functionality. The "indirect editing" solution we have now seems to work relatively well.

**Comment by PhilJdal** [comment]
Thanks. I understand the preference to edit elsewhere but I'm just speaking for the crowd that see this as a fairly basic feature of alternatives like SPSS. If you're interested in getting a large migration from existing analysis packages, they will probably want to edit the data directly.

**Comment by spacek123** [comment]
I'm not sure, where to add my "voice", but I would be plead for some improvement of editing functions too. Or even some revision of data-file model/metadata. E.g. I have big issue with ordinal variables with labels. I want students to be able to use JASP & table editor software only (no SPSS), but its hardly managable.
I can import SPSS data with values&labels, but than students couldn't edit them (without SPSS), or we need to flat them to values only (CSV/ODS etc.). Neither solution is good.

**Comment by EJWagenmakers** [comment]
I'm not sure I understand. So you import a .sav file into JASP, and then you click "edit data" (perhaps after saving to a .jasp file) and you use, say, LibreOffice Calc to edit the data. What information is lost? Maybe you can provide a .sav file and explain what currently doesn't work?
E.J.

**Comment by spacek123** [comment]
Maybe I'm doing something wrong. So, I import .sav file into JASP. Even save it as a .jasp file. When I click "edit data", SPSS will be used. To bring LibreOffice Calc, I have to convert data into .csv or .ods, but to do this, I have to choose, whether to save ordinal variables as string (labels) or as numerical value.
However, I would like to somehow keep both information in file. Numerical value, because it contains information about order of categories (and sometimes, ordinal variables are used as if they are numerical) AND value label, because its better for outputs and orientation...
I'm not sure, if it is clear... Maybe I'm missing some part of current functionality (e.g. how .jasp file work)...

**Comment by EJWagenmakers** [comment]
If you click "edit data", your favorite editor will be used. If you go to the hamburger menu and select "Preferences" you can set your spreadsheet editor. So what if you save to .jasp and open with Calc?

Also, I am not sure what you mean with wanting to retain both labels and numerical value. Can you give a concrete example? For instance, take a Likert scale. Data can be stored as strings ("disagree", "don't care", "agree") or as numbers (1="disagree", 2="don't care", 3="agree"). But if the data are in a single column, how can you store both labels and numbers? In JASP you can edit labels, by the way. 
E.J.

**Comment by spacek123** [comment]
Thanks. I knew this options but you encourage me to try it again. And it finally works.
Maybe the issue is a little opacity (from user point of view) of how .jasp file format works together with imported data. Had I to remove original SPSS file to force JASP to generate new csv file? Is my understanding correct, that .jasp file contains both data and metainformations? If yes, what is relationship between data in .jasp file and linked data from .csv file?
Thanks

**Comment by boutinb** [comment]
Hi @spacek123 
When you import a file into JASP (CSV, SPSS or ODS files), JASP keeps the data, and also where the file was read: you can see this information in File/Sync Data/Current. When you double-click the data in JASP, it automatically opens this file with (per default) the program associated with this file (it will for example automatically open SPSS for sav file). You can edit the data, and when you save it, JASP should automatically synchronize the changes you made.
If you send your JASP file to someone, you can also send the data file. If the path to the data file is not the same anymore, you can change this in File/Sync Data/Computer so that JASP is linked to the right data file again.
It is also possible to do the following: you have 2 data files with the same columns, and you want to do the same analyses with both files. Just import the first file into JASP, make your analyses. Then in File/Sync Data, choose the second data file, and JASP runs automatically the same analyses with the second file.

Bruno

**Comment by spacek123** [comment]
Thank you!
I understand reluctance to open Pandora's box of data transformation;)

Maybe, do you have any tips on good instruments how to work with data in .ods or .csv format? What standard spreadsheets editors are painfully lacking is from my point of view especially:
1) ability to deal with missing data correctly (e.g. in "average" or "sum" function of many variables etc.)
2) easy way to add new variables in large dataset (copy+long scrolling down...)

Thanks

**Comment by EJWagenmakers** [comment]
I personally like Calc, but we will add some editing capabilities specifically for those kinds of tasks for which standard spreadsheet editors are poorly equipped.
E.J.

**Comment by AlexanderLyNL** [comment]
Compute column and filtering does the job:

https://jasp-stats.org/download/
