### ISSUE TITLE
Microsoft Visual C++ Runtime Library Runtime Error!

### ISSUE THREAD

**Issue by wolfgangII** [jasp-stats/jasp-desktop#2286]
Hi,

when opening JASP I get the following window:

"Microsoft Visual C++ Runtime Library
Runtime Error!
Program: C:\Program Files\JASP0.8.5.1\JASP.exe This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information."

On "OK" click the program closes.

Would you please help me? Thank you.

* JASP version: 0.8.5.1
* OS name and version: Windows 10 Pro Version 1709
* Analysis: none
* Steps to reproduce:  opening JASP

![jasp_error](https://user-images.githubusercontent.com/36079307/35742605-46dcbbee-083b-11e8-87f5-f9d0ab8b24dd.jpg)

**Comment by boutinb** [comment]
Hi @wolfgangII, The JASP Engine cannot be started for an unknown reason... I send you a zip file that contains a bat file. Can you copy this bat file in the folder where JASP is installed (c:\Program Files\JASP0.8.5.1)? This (simple) bat file just set some settings so that the JASP Engine can be directly started from the command line. Double-Click this bat file, and tell me what the outcome is. I hope we can get then more information about your problem.
[runEngine.bat.zip](https://github.com/jasp-stats/jasp-desktop/files/1694441/runEngine.bat.zip)

**Comment by boutinb** [comment]
Thank you really much for your answer: I know now what is going on (cf: https://stackoverflow.com/questions/38045857/boostinterprocess-exception-library-error-exception-when-creating-shared-mem), and I can reproduce this problem. Some other users reported this problem, but never answered me afterwards (I think because this error can suddenly disappear if a 6005 error comes up from another application and is registered in the Windows System Log). This is a really weird bug in the BOOST library we use (and apparently not yet solved in the last version of BOOST).
I will apply the workaround described in the link.
For you, I have to have a look whether I can make a utility that can generate this 6005 error.

**Comment by boutinb** [comment]
[fixBoostBug.zip](https://github.com/jasp-stats/jasp-desktop/files/1699229/fixBoostBug.zip)
I have made a little program that generates a system log event with a 6005 error. For this you need to unzip this attachment, and run the executable with a command prompt with Administrator privilege (from the start button of Windows, right-click the Command Prompt, and choose Run As Administrator. With this command prompt run the fixBoostBug.exe. You should see:
       Hello World!
       has hEventLog
       reportEvent true

After having run this executable, start JASP again.
Tell is that works.

**Comment by wolfgangII** [comment]
Hi Bruno,

Thank you for the message. Unfortunately, on running fixboostbug.exe I get the message copied bellow. I even tried compatibility troubleshooter (built in Windows), it indicated it is Windows 8 program but stated "incompatible program" and could not run it.

Thank you for further help.

Best regards,

Wolfgang



C:\Windows\System32>d:/fixboostbug.exe
This version of d:\fixBoostBug.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by boutinb** [comment]
Hmm I don't have Windows 8, only Windows 7 or Windows 10... Can you try this one?
[fixBoostBug.zip](https://github.com/jasp-stats/jasp-desktop/files/1711821/fixBoostBug.zip)

**Comment by wolfgangII** [comment]
Unfortunately, It produces the same output copied below:

Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>c:/fixBoostBug.exe
This version of c:\fixBoostBug.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

C:\WINDOWS\system32>

**Comment by boutinb** [comment]
OK, that will not work like that. We are busy to build the new version (0.8.6) that solves (I hope) your problem. We have here a beta version: https://static.jasp-stats.org/JASP-0.8.6.0-Setup.exe. Can you try it?

**Comment by wolfgangII** [comment]
Hi Bruno,

the reported bug has been solved in version 0.8.6, thank you. However, there is another bug, see enclosed screen, the result and help windows are black. Thank you for your furher help.
![jasp_error2](https://user-images.githubusercontent.com/36079307/36341644-b75c96a2-13f1-11e8-8d3c-972623e44f7f.jpg)

**Comment by boutinb** [comment]
Hi @wolfgangII Do you run on 32 bit or 64 bit Windows machine? Can you give me the output of your System Summary? And can you give also your Region Settings (Formats & Location)?
I have seen that the WebEngine we use for the result and help, can generate a black screen for some locale (https://bugreports.qt.io/browse/QTBUG-54397). This is due apparently to a Chromium problem (https://bugs.chromium.org/p/angleproject/issues/detail?id=1433). If this is your problem, maybe it may help to change the Region settings of your PC.

**Comment by AlexanderLyNL** [comment]
Concretely, could you please temporarily change your region setting to English, or the decimal from "," to "." and try running JASP? If this removes the black screen, then we've identified the problem.

**Comment by FransMeerhoff** [comment]
HI @wolfgangII 

We are planning to release JASP 0.8.6 next week.
We have added a line in the code that might solve this black screen issue.
You can find this setup on  https://static.jasp-stats.org/JASP-0.8.6-Setup.exe
Would you be so kind to tests this version for us?

Kind regards
Frans Meerhoff

**Comment by wolfgangII** [comment]
Now everything is OK. Thank you.
