### ISSUE TITLE
Test ANOVA

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-desktop#2306]
Test ANOVA analysis for new release

**Comment by Janto91** [comment]
1. If one specifies simple effects for interaction effects that are not part of the model, there is no information given that the interaction effect is not part of the model. I think a footnote could be helpful for this case.
2. I wonder why there is a limit to the number of moderators one can specify for the simple main effects, while the number of factors for the actual ANOVA is not limited.
3. For the following warning "Singular fit encountered; one or more predictor variables are a linear combination of other variables", it would be good to know for which variables this applies.
4. In an ANOVA with DV = V1, IVs = contBinom, facGender, facExperiment, and facFive, there is a warning "Singular fit encountered; one or more predictor variables are a linear combination of other predictor variables", but still all effects are estimated. However, post-hoc tests are not conducted.
5. In an ANOVA with DV = V1, IVs = contBinom, facGender, facExperiment, facFive, and debString, no 3-way, 4-way, and 5-way interaction effects are estimated and it is not clear why.
6. For corrections of p-values in post-hoc tests (for example Bonferroni), it might good to provide a footnote with the number of the tests used for the correction (only the number of tests for the same variable or number of tests for all variables for which post-hoc tests were conducted).
7. If no correction is checked for post-hoc tests, no p-value is shown. There should be a default option that is shown in this case.
8. Very minor: For descriptive plots, "confidence interval" is checked even before "Error bars displaying" is selected. I also wonder whether it might be better to say "Display error bars" instead of "Error bars displaying".
9. Maybe one could give "additional options" a more meaningful name. Maybe move "additional options" more to the top, directly above or below "model" as the effect sizes belong to the ANOVA table.
10. For Additional options / Marginal means, change "Compare main effects" to "Compare marginal effects to 0"
11. For contrasts, I think there should be a list of options that people can choose from rather than having to write a word. Especially since there are no further information on which options are accessible.
