### ISSUE TITLE
Descriptive Plots: first data point is not in data

### ISSUE THREAD

**Issue by stjep** [jasp-stats/jasp-desktop#2349]
## Template for bug reports

* JASP version: 0.8.5.1
* OS name and version: macOS 10.13.3
* Analysis: Repeated Measures ANOVA
* Steps to reproduce: Descriptive plot where the horizontal axis is the within factor and the separate lines are the between factor, the first point in the plot is not in the data. Attached screenshot shows the plot, and the descriptives. The second point in the plot is actually the means from the first cells.

----

**JASP plot**
<img width="525" alt="screenshot 2018-02-20 18 44 23" src="https://user-images.githubusercontent.com/3305421/36415153-847f46a4-1670-11e8-9676-6d7f1f06fbbb.png">

----

**Excel plot**
<img width="823" alt="screenshot 2018-02-20 19 11 16" src="https://user-images.githubusercontent.com/3305421/36415500-d8fd84b0-1671-11e8-95db-d9c3ea9a5306.png">

[ext_diff.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1739481/ext_diff.jasp.zip)

**Comment by boutinb** [comment]
@stjep Can you send us the data file and the JASP file as well (in a zip format, you can attach it in a comment of this issue)?

**Comment by stjep** [comment]
The JASP file is attached as a .zip to the original issue and here. The data file is additionally attached here.
[ext_diff.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/1749839/ext_diff.jasp.zip)
[ext_diff.csv.zip](https://github.com/jasp-stats/jasp-desktop/files/1749840/ext_diff.csv.zip)

**Comment by Janto91** [comment]
@stjep: Thank you for sending us the files and reporting about your problem! I think the discrepancy between the two plots is caused by the order in which the variables were entered. In the JASP file you sent us, ext_diff_20 was actually the first data point. If I change the order so that ext_diff_20 is the last data point, it looks pretty much like the Excel plot above.

![ext_diff_image](https://user-images.githubusercontent.com/21968125/36908551-d8570bae-1e3b-11e8-9939-6805acf039c2.png)

Please let me know if I misunderstood your question or if you have further questions.
