### ISSUE TITLE
Cannot open JASP 0.8.6.0

### ISSUE THREAD

**Issue by astefan1** [jasp-stats/jasp-desktop#2379]
Dear JASP team,

today, I wanted to download the new JASP version (0.8.6.0), but JASP crashes every time I try to open it. I tried both the installer and the zip file, but as soon as the JASP.exe is executed and JASP opens, I receive an error message ("JASP has experienced an unexpected internal error") and the only thing I can do from then on is to close the program.

I run Windows 8.1 on my computer. I suspect that the Windows firewall detects some issues with the program, because if I start the program manually from the .exe that I extracted from the .zip file, Windows warns me about the properties of the program.

Here's a screenshot of the error message: https://www.facebook.com/photo.php?fbid=1720113511381868&set=p.1720113511381868&type=3&theater&ifg=1

It would be interesting to know if other people experienced similar issues and how to solve this.

Cheers,
Angelika

**Comment by boutinb** [comment]
@astefan1 Apparently, the JASP Engine cannot be started for an unknown reason... I send you a zip file that contains a bat file. Can you copy this bat file in the folder where JASP is installed (c:\Program Files\JASP0.8.6)? This (simple) bat file just set some settings so that the JASP Engine can be directly started from the command line. Double-Click this bat file, and tell me what the outcome is. I hope we can get then more information about your problem.
[runEngine.bat.zip](https://github.com/jasp-stats/jasp-desktop/files/1771005/runEngine.bat.zip)

**Comment by boutinb** [comment]
@astefan1 Could you install this Visual Studio redistributable: https://aka.ms/vs/15/release/vc_redist.x64.exe (if you have 64 bit computer)
https://aka.ms/vs/15/release/vc_redist.x86.exe (if you have 32 bit computer)

**Comment by astefan1** [comment]
Hi @boutinb,

when I double-clicked on the bat-file, I first received the same Windows warning message (unknown source) as before when I tried to open JASP. Then, when I overrode that warning, the command line opened. In the command line, there are lots of paths shown and the last line says "null".

I'll install the Visual Studio right away and tell you what happens next.

**Comment by astefan1** [comment]
Yay, now it starts normally! Thanks a lot!

**Comment by AlexanderLyNL** [comment]
Does the normal installer work? Or do you still need to use the zipped version?

**Comment by boutinb** [comment]
These redistributable libraries are per default downloaded with all applications using Visual Studio, and all PC's where we tested JASP had these libraries, and did not see this mistake. We'll change our setup to include these libraries.

**Comment by astefan1** [comment]
The normal installer worked just fine for me. I had just checked the zipped version in the beginning to make sure it is not an installer problem.

**Comment by FransMeerhoff** [comment]
Hi Alex,

It has nothing to do wit the zipped version or the installer.
Because we now use the Visual Studio compiler we need some redistributables of VC
We have send that link to here in problem issue.
We are updating the setup for this.

Cheers Frans

On 1 Mar 2018, at 13:42, AlexanderLyNL <notifications@github.com<mailto:notifications@github.com>> wrote:


Does the normal installer work? Or do you still need to use the zipped version?
