### ISSUE TITLE
Data Files are not saved in the selected location

### ISSUE THREAD

**Issue by dietrichstats** [jasp-stats/jasp-desktop#2386]
## Bug report

**JASP version:** 0.8.6 (Flatpak)

**OS name and version:** Solus OS 4 (gnome)

**Description:** The JASP files are not saved in the specified location, but in "`/run/user/1000/doc/xxxxxxxx`". The files are accessible via "Recent Files".
On the other hand, exporting _results_ and _data_ works perfectly.

**Steps to reproduce:** 
- Open a Data File
- Go to "`File|Save as|Computer|Browse`"
- Select a location and save
- Go to the location where the document was saved

**Current result:** The Data File is not found, but it is visible from "Recent Files" in JASP

**Expected result:** The document is saved in the previously selected location

**Note:** As a small improvement, it would be good if the extension were added to a CSV file, since JASP doesn't recognize that type of files without an extension in "`Open|Computer|Browse`".

**Comment by boutinb** [comment]
I cannot reproduce this problem on Mac or Windows, @JorisGoosen: can you try this with an Flatpak installed version?

**Comment by haevalencia** [comment]
I can confirm this in Fedora, I had not realized since I usually work with CSV or SAV files,

**Comment by JorisGoosen** [comment]
I can confirm that the saving is a bit confusing right now and seems to go wrong for jasp-files. However a workaround for now is specifying explicitly in the save-dialog that it should end in ".jasp".

So when saving "analyses" you will not find analyses.jasp where you expect it, try saving it as "analyses.jasp" and then it will show up where you thought it would.

It will however still be shown with a /run/user/etcetera path in recent files and will not be openable from there. This is due to the way the sandboxing of a flatpak is set up. I will investigate further and see if that can be mitigated.

**Comment by dietrichstats** [comment]
@JorisGoosen The proposed temporary solution works very well. I remember that in the first stages of development of LibreOffice in Flatpak format something similar happened in how the recent folders were shown, so I suppose it is something approachable.

Links of interest:
- https://lists.freedesktop.org/mailman/listinfo/flatpak
- https://whatofhow.wordpress.com/

**Comment by JorisGoosen** [comment]
I will take a look at how they solved it and see if we can do something similar. I also some some related issues on flatpaks github: https://github.com/flatpak/xdg-desktop-portal/issues/141

There seems to be something else wrong though because I get some strange errors when loading a saved .jasp file (as in issue #2401).

**Comment by JorisGoosen** [comment]
paths are shown correctly and can be accessed through recent files etc
