### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zhengjiji456** [jasp-stats/jasp-desktop#2390]
The 0.8.6 version can not be installed on my Mac. However, the 0.8.5 version works well.
* JASP version:0.8.6
* OS name and version:Mac OS X 10.9.5 (13F34)
* Analysis: none
* Steps to reproduce: none

Dyld Error Message showed when I open the 0.8.6 version
  Library not loaded: /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
  Referenced from: /Applications/JASP.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Reason: image not found

**Comment by FransMeerhoff** [comment]
HI @zhengjiji456 

This is problem is probably caused by the version of Mac OSX 10.9 you are running.

See the information below:
https://bugreports.qt.io/browse/QTBUG-61981
Qt 5.9.0 (we are using Qt 5.10.1 on the latest JASP 0.8.6 version) has a minimum requirement of macOS 10.10, and CoreBluetooth was added in 10.10 as can be seen here: https://developer.apple.com/documentation/corebluetooth
You are running the application on macOS 10.9, which doesn't have the framework. 

So please upgrade you Mac manualy to the latest version (via App Store -> Updates) and 
your problem will probably be solved.

Kind Regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @zhengjiji456 

Could you please tell us what the status of this issue is?

Cheers  
Frans Meerhoff

**Comment by zhengjiji456** [comment]
Hi Frans Meerhoff,
Thanks for your email and your quick response to my issue.
I did not upgrade my Mac to the latest version for some personal reasons. Now I run the newest JASP on windows. 

Best regards,

Ji

----- 原始邮件 -----
发件人: "FransMeerhoff" <notifications@github.com>
收件人: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
抄送: "zhengjiji456" <zhengjiji456@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期二, 2018年 3 月 13日 下午 4:03:01
主题: Re: [jasp-stats/jasp-desktop] Installation error (#2390)

Hi @zhengjiji456 

Could you please tell us what the status of this issue is?

Cheers  
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @zhengjiji456 

OK, thanks for the info. I understand.
I close issue and reopen when this problem reoccurs.

Best regards
Frans
