### ISSUE TITLE
E notation does not look good in BAS table

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2394]
@vandenman 
See screenshot: the e-notation is not pretty with the extra space.
Cheers,
E.J.
![enotation](https://user-images.githubusercontent.com/8603015/37005394-32f0b336-20d4-11e8-8608-e0919b13a5f6.png)

**Comment by vandenman** [comment]
This doesn't look like an R problem, but rather something that needs to be figured out in the javascript.
However, it could be that this is again the high def screen issue, as it looks a lot less bad on my screen:

![image](https://user-images.githubusercontent.com/21319932/37037472-a6111be8-2152-11e8-9bbf-66bb7c6fabd8.png)

@boutinb any ideas?

**Comment by boutinb** [comment]
Probably a high DPI problem... JASP uses a 'thin space' between the 'e' and the exponent. This 'thin space' (a &thinsp in HTML) is usually defined as ​1⁄5 or ​1⁄6 of an 'em' in width (an 'em' should be the width of a character). But apparently, this conversion width does not work with high DPI on Windows...
But I don't understand why this this space is used. I would say that the exponent should use a superscript HTML tag (<sup>). We have to try this method, and test it on every kinds of computer, especially EJ computer!

**Comment by boutinb** [comment]
The superscript HTML tag was not a good idea. But we can, I think, just remove this thin space.

**Comment by boutinb** [comment]
@EJWagenmakers I had a look again to this problem. In the screenshot you gave, we cannot see the whole table. JASP tries to align the exponent with the whole column: look here:
<img width="556" alt="screen shot 2018-03-08 at 10 58 30" src="https://user-images.githubusercontent.com/503332/37144918-c214227c-22bf-11e8-9627-3a22d4e26d58.png">
In this table, I have exponents like -4 and -10. JASP adds a space before the -4 so that the numbers stay aligned for the whole column. I suspect that some of your numbers have also exponents with 2 or 3 digits, making this extra spaces.

**Comment by EJWagenmakers** [comment]
OK. But is this the best choice? An alternative is to simply start from the right of a column. This will make the entries look more ragged though. What do you think, @akashrajkn @vankesteren ?

**Comment by vankesteren** [comment]
I actually like the way it's displayed now.

**Comment by vankesteren** [comment]
I am closing this issue. If people disagree, we can reopen it 😄
