### ISSUE TITLE
Error in loadNamespace (name): there is no package called 'emmeans'.

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-desktop#2458]
* JASP version: last jasp-desktop-development
* OS name and version: Win 10 Pro (ITA)  ver. 1709  build 16299.309 
* Analysis: Repeated Measures ANOVA

Hi Jasp developers,
above all, thank you for your great work.

I'm interested in new features waiting for the next jasp update, and in particular to try the nonparametric options for ANOVA.
I followed the "Guide to Building JASP" for windows and tried for the first time compiling jasp-desktop-development.
The result of the build (debug mode), is not particularly satisfactory, given the presence of the error message (as shown in the screenshot):
Error in loadNamespace (name): there is no package called 'emmeans'.

Where am I doing wrong?
Thanks again for your help.

Greetings,
Maurizio
![screenshot 2018-04-08 15 25 33](https://user-images.githubusercontent.com/36552289/38468973-e76cbff6-3b4d-11e8-9be1-1b6e289f31be.png)

**Comment by MAgojam** [comment]
Hi Alexander,
thanks for your quick reply.

I copied the "emmeans" folder in Jasp's directorry as you suggested, resolving the reported error.
Another error appeared that indicated the presence of "estimability" version 1.2, suggesting the need to use a version> = 1.3.
I also made this change, replacing the 1.2 with the latest 1.3 of "estimability".

Now I receive the following msg error (see screenshot):
This analysis terminated unexpectedly.
Error in ref_grid (object, ...): Can not handle an object of class 'afex_aov'
![screenshot 2018-04-11 22 18 08](https://user-images.githubusercontent.com/36552289/38641349-08ae8308-3dd7-11e8-93d3-bbb64e9beb49.png)

Thanks for your patience.

Greetings,
Maurizio

**Comment by AlexanderLyNL** [comment]
Hi Maurizio,

Sorry for doing this so clunkily and in such a dumb stepwise session. The reason is that we're still working on some minor issues and ironing out the process, so the best thing to do is wait a couple of days. However, if you don't mind helping out with a bit of testing, you can also upgrade to what we're trying to do now, by 

- Downloading our new R package: https://static.jasp-stats.org/development/R3.4%20Win%20JASP%200.8.7.zip
- Put this in your R directory as explained here: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-building-guide.md
- Rebase: Because an update of R3.4 is included 

Let me know if this works or whether you'd prefer to wait a couple of days. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
The comment by Johnny gives some background to the error: 

https://github.com/jasp-stats/jasp-desktop/issues/2412

**Comment by MAgojam** [comment]
Hi Alexander,
thanks again for your time.

Now it's ok (see screenshot).
![screenshot 2018-04-12 23 45 44](https://user-images.githubusercontent.com/36552289/38706541-db4ab0bc-3ead-11e8-91e8-8c743df4e208.png)

I can continue to explore and my students will be happy about this and wait to be able to download jasp 0.8.7

Greetings,
Maurizio

**Comment by AlexanderLyNL** [comment]
Hi Maurizio,

Thanks for the feedback. Glad that it works! Please let us know if you're interested to develop for JASP. The current framework is a bit opaque and will be replaced soon. Documentation can be found here: https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/r-analyses-guide.md

For clarity, does JASP 0.8.6 suffices for your students needs?

Cheers,
Alexander
