### ISSUE TITLE
B 1S T-Test: error with a particular analysis

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#256]
using ssgo-fred.csv

![screen shot 2015-02-05 at 8 19 06 pm](https://cloud.githubusercontent.com/assets/3240247/6067383/5803919c-ad74-11e4-9f17-9167de0347e5.png)

**Comment by jonathon-love** [comment]
this is possibly a related issue

![screen shot 2015-02-05 at 8 20 37 pm](https://cloud.githubusercontent.com/assets/3240247/6067394/7c469ab8-ad74-11e4-96e3-f0bf1779d765.png)

**Comment by quentingronau** [comment]
This happens when the evidence is so clear in favor of the hypothesis that is not tested, that there are very little or even zero posterior samples in the tested interval. I'm not completely sure how to handle it: For the 1-sample and paired-sample t test it should be possible to add a footnote. For the independent samples  t test however, the table with the results and footnotes is an own function and is produced before the plots are created. I could display an error message, but this would prevent all other selected plots from being displayed, right?

**Comment by jonathon-love** [comment]
hmm, not sure. come and chat to me about this one next time you're in.
