### ISSUE TITLE
Broken link to file type

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2615]
So I just installed the 0.9 version and uninstalled the earlier versions. 
Now when I click on a .jasp file, I get an error message saying that the file type is not associated with an application. Apparently the .jasp format was associated specifically with the 0.8.6 version. Still this is a little awkward.
See screenshot
![image](https://user-images.githubusercontent.com/8603015/41218692-336ccc6c-6d5c-11e8-910f-5bf6d9b558d2.png)

**Comment by AlexanderLyNL** [comment]
This is of course suboptimal, but file association is organised by the OS. Hence, it might be just your windows. @Kucharssim @koenderks have you encountered the same problem?

**Comment by boutinb** [comment]
I have just tried it (uninstall and install JASP on Windows), and if I double-click on a JASP file, it opens JASP normally. I see also that the file association is well removed when JASP is uninstall, and that is set back after installation. So I think I need laptop of EJ to understand what's happening there...

**Comment by koenderks** [comment]
No, my version 0.9 opens .JASP files normally.

**Comment by Kucharssim** [comment]
I can replicate the error. The error occurs when I install 0.9 and AFTER that I uninstall 0.8.6 (but not the other way around).

Note that also when I did not uninstall 0.8.6, the default application to open .jasp files stayed 0.8.6 instead of updating to 0.9. I think that previous versions always override the default application so that the most recent version is used even if older JASP versions are still installed.

**Comment by AlexanderLyNL** [comment]
See Sheet
