### ISSUE TITLE
multinomial not calculating properly

### ISSUE THREAD

**Issue by coledavis** [jasp-stats/jasp-desktop#2646]
## Template for bug reports
* JASP version: 0.9
* OS name and version: Windows 10
* Analysis: multinomial
* Steps to reproduce: 
Data: 28, 42, 80 
The observed data is 0.333, 0.333, 0.333, the same as the expected data.  So of course we get a chi-square = 0 and a p = 1.  This set of data should of course be significant. 

![image](https://user-images.githubusercontent.com/16545617/41735874-c2e62d24-7582-11e8-9f30-b05b0bcf31fe.png)

**Comment by EJWagenmakers** [comment]
@vankesteren 
I believe this happened because the multinomial requires you to have a "factor" (say month, or group) as well as "counts". You can view an example in the JASP data library, under Frequencies and then "Memory of Life Stresses". I've also attached a screenshot for your data. So I don't think this is a bug, although it does seem to me that there should not be any output when only the group factor is added (or only the counts are provided, but not the factor).

 
![multinomial](https://user-images.githubusercontent.com/8603015/41738460-653fbfae-7592-11e8-9c09-d90d385926b3.png)

**Comment by coledavis** [comment]
I tried that before and got a worse result! 
![image](https://user-images.githubusercontent.com/16545617/41739404-ddc2abea-758c-11e8-9b96-6ef415090a34.png)
![image](https://user-images.githubusercontent.com/16545617/41739447-fa965348-758c-11e8-8cd2-ffccab3650e0.png)
And yet, I have the same amount of factor as counts. 
![image](https://user-images.githubusercontent.com/16545617/41739496-2336ed4e-758d-11e8-9c8e-04ed5c173790.png)

**Comment by AlexanderLyNL** [comment]
Perhaps it's the drinks, but if the null hypothesis is 1/3 and the data also result in 1/3, the p-value should be high, thus, not significant, and I think p=1 is fine. The p-value is a measure of divergence of what is expect and the lower it is, the more it diverges. In this case, the observed and expected are the same, so the p-value should be high, shouldn't it?

**Comment by coledavis** [comment]
Ah! Got it! (No drink today.)  It is rather a long time since I've used JASP. What was the problem is that I used a file with lots of different-sized variables. Like R, JASP doesn't like it, presumably assuming a lot of N/As. If I just have one file with the two variables, it works fine. Sorry.

**Comment by vankesteren** [comment]
Hey all,

Because we wanted to remain `flexible`, the multinomial test accepts 2 kinds of data:

1: no counts added -> number of occurrences in the factor variable considered as counts. A factor variable can look like this:

| factor |
| :----: |
| A | 
| B | 
| B | 
| A | 
| C |
| A | 
| C | 

2: counts added -> each level of factor gets the counts specified by "counts":

| factor | counts |
| :----: | :----: |
| A |  3 |
| B |  2 |
| C | 2 |

These two kinds will produce the **same results**.


If you add counts to a factor like in condition 1, it will give an error because the levels are indicated more than once. 

If you think this behaviour is counterintuitive, let us know what we could improve!

**Comment by akashrajkn** [comment]
@vankesteren could you add that to the helpfile?
