### ISSUE TITLE
No option for 95% CI within the descriptive statistics

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-desktop#2672]
* JASP version: 0.901
* OS name and version: openSUSE Tumbleweed flatpacked
* Analysis: No option for 95% CI within the descriptive statistics
* Steps to reproduce: with any dataset click descriptives > descriptive statistics > statistics section 

* Enhancement: Add a button for the 95% CI next to or below the S.E. mean button. My students argue that this would be more useful in practice than the S.E. mean. I know its not hard to calculate times 2, but the students have a point - 95% CI is just more common to report.
* Purpose: Its easier to explain my students why they should learn something, when its widely used.

**Comment by AlexanderLyNL** [comment]
Hi Thomas,

I’ve improved the Descriptives so it’ll show the 2.5 and 97.5% quantiles (next edition), which shows how concentrated a variable is. To get confidence intervals, you can run one of the analyses. 

I do not intend to add confidence (or credible) intervals in the descriptives module of JASP, because formally a confidence interval defines the interval of parameter values for which a null hypothesis does not reject. Thus, to calculate a confidence interval, we need to know which parameter the user is interested in and assume a distribution for the data. This we believe is not part of the exploratory nature of the descriptives, but part of one of the other analyses we provide. If people are interested in the confidence interval of the mean of a variable, then they can analyse this variable using a one-sample t-test, while they should use the Bayesian one-sample t-test, if they’d like a credible interval instead. 

Cheers,
Alexander

**Comment by tomtomme** [comment]
Hi Alexander,
you already have a confidence interval in there. It is called S.E. mean and is the 68% confidence interval. I asked to display the 95% interval of the mean instead, because in an univariate analysis nobody would ask for the 68% one. If your argument still stands, you would have to remove S.E. mean from the descriptive section.
However, to search for a confidence intervals within a t-test sounds not very intuitive for me.
Cheers, Thomas

**Comment by AlexanderLyNL** [comment]
Hi Thomas, 

There might be some misunderstanding here. By standard error of the mean, we refer to the estimate of \sigma/\sqrt{n}, where we plug in for the population standard error \sigma the sample standard deviation. This does not imply that the procedure that outputs the interval 

	C(data)=(mean(data) - s.e. mean (data), mean(data) + s.e. mean (data))

encapsulates the population mean with 68% coverage. In fact, it’s almost surely never a 68%-confidence interval not even if the data are normally distributed and the sample standard deviation s is exactly equal to its population value \sigma. The chance of the sample standard deviation s being equal to \sigma occurs with 0%. The procedure leading to the interval C might have very low coverage, say, 20%. 

When the data consists of Likert scale measurements, say, from 1 to 5, then the interval C(data) will definitely not be a 68%-confidence interval. Furthermore, if your data are binomial consisting of 4 ones and 1 zero, then you get 
	
	mean(data) = 0.8 
	s.e. mean(data) = 0.2

The upper bound of the proposed 95% confidence interval would then be mean(data) + 1.96 * s.e. mean(data) = 1.192, which wouldn’t make sense since the parameter of the binomial cannot be larger than 1. 

To add a % statement to an interval you need to have a model. A confidence interval is in essence a hypothesis test, which is why it belongs to an analysis and not to Descriptives. 

Cheers,
Alexander

**Comment by tomtomme** [comment]
Interesting. On the first and second read, I do not think that I really understand what you are saying. For me it always made sense to say "mean(data) +/- 1 * s.e.  covers 68%", because the standard normal distribution shows exactly that. The distribution of means is thinner than the standard normal distribution, but it also applies there I thought.

Also, what do you mean with "you need to have model". The moment I replace sigma (population standard deviation) with s (sample standard deviation) I already have a model. Because this is a "punktschätzer" / point estimate.
