### ISSUE TITLE
Filter compressed too much?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#2754]
Reducing the width of the data panel compresses the Filter until the symbols overlap. Not a big problem but still...See attach
E.J.

**Comment by EJWagenmakers** [comment]
And now with the attachment...
![filtercompression](https://user-images.githubusercontent.com/8603015/44664872-c40c2c00-aa14-11e8-8a29-613d2a2da6c7.png)

**Comment by JorisGoosen** [comment]
Yeah, this is a bit of a stumper until the panel redesign is done.

Actually when you have a analysis form open it *should* cover the dataview and thus the filter but this doesn't work perfectly. It is also a bit hard to know what to expect. When the filter gets compressed that much then I don't know what to do about it.

I could simply blank the filter and show a "Make me bigger <--->" message of some kind. Because right now the mix of QML and QtWidgets makes it impossible for me to force minimumsizes and other stuff for the dataview/filter/computecolumn panel.

**Comment by AlexanderLyNL** [comment]
This will eventually be fixed.
