### ISSUE TITLE
Error when exporting high res figures

### ISSUE THREAD

**Issue by tvantimmeren** [jasp-stats/jasp-desktop#2776]
When I try to export graphs to high-resolution format (tiff, pdf, eps), JASP experiences an ‘unexpected internal error’. Exporting to PNG works just fine.

I've tried with different versions on Windows 7 and Mac OSx, see details below. 

Windows:
* JASP version: 0.8.6.0
* OS name and version: Windows 7
* Analysis: Repeated Measures ANOVA
* Steps to reproduce: 'Save Image As' > tiff / pdf / eps. JASP immediately experiences an ‘unexpected internal error’ and says it cannot continue.

On Mac:
* JASP version: 0.9.0.1
* OS name and version: MacOS 10.13.6
* Analysis: Repeated Measures ANOVA (but doesn't seems to be limited to this analysis) 
* Steps to reproduce: 'Save Image As' > tiff / pdf / eps. >> 4 new JASP windows open with what looks like a high-res image, but they are not responding, so I can only force quit. The original JASP window experiences an ‘unexpected internal error’ and says it cannot continue.

[MIDT_task_Results_JASP.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/2386449/MIDT_task_Results_JASP.jasp.zip)

**Comment by AlexanderLyNL** [comment]
Hi tvantimmeren,

Thanks for reporting this. I was able to replicate this problem on my mac on JASP 0.9.0.1. The good news is that this does not occur on my development version, see attached: 

[tvantimmeren.zip](https://github.com/jasp-stats/jasp-desktop/files/2386822/tvantimmeren.zip)

On your mac, is JASP 0.9.0.1 the only JASP version for which this problem occurs? Similarly, on your windows workstation, is JASP 0.8.6, the only JASP version for which this problem occurs? 

Cheers,
Alexander

**Comment by tvantimmeren** [comment]
Hi Alexander,

thanks for the attached images. The problem occurs at least in JASP 0.9.0.1 on both OSs and 0.8.6 on Windows. I haven't tried other versions. 

Best,
Tim

**Comment by AlexanderLyNL** [comment]
Hi Tim,

We detected a small bug in our builds and have found a solution. Could you please try our following experimental build and check whether this solves your issues?

https://static.jasp-stats.org/JASP-0.9.1.0.dmg

Please let me know whether it works on your mac. 

Cheers,
Alexander

**Comment by fplatz** [comment]
Hi Alexander,

I have the same problem. When saving an image, JASP calls Quartz four times and crashes. Installing your experimental build did not fix that problem on my machine.  I have installed the latest version of XQuartz. Is there any other solution available? I need my figures for a talk. Otherwise, I have to plot them in R.

Cheers,
Friedrich

**Comment by AlexanderLyNL** [comment]
Hi @fplatz and @tvantimmeren,

Here are two new experimental versions. Could you please check whether you can save plots with these builds:

Mac:
https://static.jasp-stats.org/JASP-0.9.1.0-Nightly-03-10-2018.dmg

Windows:
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(64).exe
https://static.jasp-stats.org/JASP-0.9.1.0-Setup-Nightly-03-10-2018(32).exe

Cheers,
Alexander

**Comment by fplatz** [comment]
Hi @AlexanderLyNL ,

thanks for the build. I tried the MAC-Verison just for a few minutes. Unfortunately, I got the same error message for *.eps, *.pdf *.tiff: 
"JASP has experienced an unexpected internal error.

""

If you could report your experiences to the JASP team that would be appreciated.

JASP cannot continue and will now close."

However, the four windows did not appear on my screen, thus fixing that bug seems going on but has probably not been finished right now. I think, that you're only one step away and the next release will fix it.

Cheers,
Friedrich

**Comment by AlexanderLyNL** [comment]
Hi Friedrich,

Are you using an old jasp file or a new one? If you use an old file, could you please refresh all analyses before saving again? Can you tell me which mac version and which xquartz version you're running?

Cheers,
Alexander

**Comment by fplatz** [comment]
Hi Alexander,

you're right. After having refreshed all analyses, I got an *. eps file from my results. It works fine! 
JASP is running on a Mac with an actual OS and the latest version of XQuartz. 

Thank you for your support!
Cheers,
Friedrich

**Comment by AlexanderLyNL** [comment]
I consider this issue fixed. Please reopen if reappears.
