### ISSUE TITLE
B T-Tests: Prior and Posterior Plots: could do with some tweaks

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#280]
not a big deal, but these could be tweaked a little.

![_33](https://cloud.githubusercontent.com/assets/3240247/6171137/509a1dbc-b2d9-11e4-96d8-7a1a511e5b9e.png)
![_34](https://cloud.githubusercontent.com/assets/3240247/6171136/50992f4c-b2d9-11e4-8c02-9fee0270a582.png)
![_35](https://cloud.githubusercontent.com/assets/3240247/6171138/509cc828-b2d9-11e4-8ceb-96cae004d6bf.png)

**Comment by jonathon-love** [comment]
Additional info seems to exacerbate things:

![_42](https://cloud.githubusercontent.com/assets/3240247/6171231/e09d5a6e-b2d9-11e4-8cd0-19668df5dc41.png)
![_43](https://cloud.githubusercontent.com/assets/3240247/6171230/e09a3dca-b2d9-11e4-8d76-479fb496705d.png)

**Comment by jonathon-love** [comment]
hey @quentingronau,

what do you think about this for the 0.6 ?

**Comment by quentingronau** [comment]
Hm, I think this happens when there are very few data points (< 10), because otherwise the posterior should get narrower in most cases. But of course we should find a solution. I'm not completely sure, three things came to my mind:
1) I could omit the bar on top of the posterior for less than 10 observations
2) I could change the y-coordinate of the legend to be at the middle of the y-axis for such cases
3) I could increase the range of the y-axis such that the bar is below the legend for less than 10 observations

What do you think?
