### ISSUE TITLE
Bug report: Repeated measures' descriptive plot not well plotted?

### ISSUE THREAD

**Issue by vicenteinefo** [jasp-stats/jasp-desktop#2840]
* JASP version: 0.9 jun 15 2018
* OS name and version: Windows 7 professional and also with MacOS 10.11.6 El Capitan
* Analysis: Repeated measures ANOVA
* Steps to reproduce: It could be possible that the descriptive plot displaying error bars is not well plotted? The same “bug” seems to occurs when either “Confidence interval” or “Standard error” is selected. See moment 2 data.

I have attached the JASP file, a screenshot with the plot and a screenshot with manually calculated SE and CI in Excel.

![captura de pantalla 2018-10-05 a las 9 01 08](https://user-images.githubusercontent.com/29978768/46520705-43471800-c87d-11e8-8828-6eb79af52cff.png)

![captura de pantalla 2018-10-09 a las 8 22 00](https://user-images.githubusercontent.com/29978768/46650353-739ff680-cb9c-11e8-8774-3a840185bf50.png)

[MR chart.jasp.zip](https://github.com/jasp-stats/jasp-desktop/files/2459056/MR.chart.jasp.zip)

**Comment by JohnnyDoorn** [comment]
Hi Vicenteinefo,
Can you tell me how you calculated your column labeled IC? Because there are several ways to compute these. In JASP we use a correction factor for confidence intervals for within subjects factors based on Morey (2008): http://pcl.missouri.edu/sites/default/files/morey.2008.pdf
This correction factor is equal to m / (m-1), where m is the number of within subjects levels. 
Kind regards,
Johnny

**Comment by vicenteinefo** [comment]
Hi @JohnnyDoorn,
I have calculated the CI using the excel formula CONFIDENCE.NORM.
I have also computed the CI using SPSS and returns the same result (attached screenshot)
I did not know the reference you added.
Maybe I am interpreting something wrong but, how It could be possible such a small CI in "Momento 2"? In fact, it has almost the same SD
Kind regards,
Vicente

![captura de pantalla 2018-10-09 a las 17 56 04](https://user-images.githubusercontent.com/29978768/46681935-a07bfa00-cbec-11e8-9b06-03f5190f3735.png)

**Comment by JohnnyDoorn** [comment]
Hi Vicente,
Yes, in within subjects designs this can be problematic because these methods do not distinguish between between subjects variability and within subjects variability. In order to get more accurate confidence intervals for within subjects factors, a common way to do this is by normalizing the data first, by subtracting each subjects' mean from their observations, and then adding the grand mean (across participants). This process is nicely described in this blogpost (where Morey's correction is also mentioned/recommended): https://motorbehaviour.wordpress.com/2014/10/31/confidence-intervals-in-within-participant-design-a-tutorial-on-the-cousineau-morey-method/

JASP normalizes the data before computing the confidence intervals. If you just compute the standard deviation for your momento 2, it does not seem exceptionally low. However, when you remove between subject variability by normalizing, it drops considerably.

I am not sure what SPSS does, or if that table you posted is output from the RM ANOVA. But the confidence intervals that are in there are treating each variable as separate and does not distinguish between the two types of variance (between and within subjects). I hope this clarifies things =)

Kind regards
Johnny

**Comment by AlexanderLyNL** [comment]
I consider this fixed. Please reopen if issue reappears.
