### ISSUE TITLE
B ANOVAs: Add option for the forward and backward stuff in the analysis of effects table

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#292]
@EJWagenmakers , cc @mmarsman1 

shall we drop these columns out of the analysis of effects table for the 0.6?

we could add in an option for them instead, but we don't have docs explaining them, etc. it might just be easier to drop them out for now.

**Comment by mmarsman1** [comment]
I agree that it is unclear what they are.
However, they are talked about in the webpage that you provided earlier:
https://static.jasp-stats.org/about-bayesian-anova.html
Is that not made available for the general public?

If they are unclear, then including them in “options”  is as unclear of course.

On 14 Feb 2015, at 21:39, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


@EJWagenmakers<https://github.com/EJWagenmakers> , cc @mmarsman1<https://github.com/mmarsman1>

shall we drop these columns out of the analysis of effects table for the 0.6?

we could add in an option for them instead, but we don't have docs explaining them, etc. it might just be easier to drop them out for now.

**Comment by jonathon-love** [comment]
> Is that not made available for the general public?

not really. when people ask me, i send the link to them. otherwise there's not really a way to find it.

**Comment by EJWagenmakers** [comment]
I was hoping we could keep them in but show them only when the users
selects that option. We will explain their use in the PBR paper.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by mmarsman1** [comment]
It is an easy fix on my end.
It seems a waste not to include stuff that's allready available.
I do agree that they should be explained somewhere, because without that it may be confusing in the table.

Verzonden van mijn HTC

----- Reply message -----
Van: "EJWagenmakers" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] B ANOVAs: Proposal to temporarily remove the forward and backward stuff in the analysis of effects table (#292)
Datum: zo, feb. 15, 2015 12:21

I was hoping we could keep them in but show them only when the users
selects that option. We will explain their use in the PBR paper.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
Can't we have a help tab, and copy-paste the text that I provided earlier?
It is not perfect but it is something, and it signals that we are working
on it.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
What should the option be called?

    Output
      [  ] Effects
         [  ] Backwards and forwards thing

**Comment by EJWagenmakers** [comment]
Stepwise

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
@mmarsman1, the option in R is called `effectsStepwise`
