### ISSUE TITLE
Proposal to include log(BF) alongside BF₁₀  and BF₀₁ in all Bayesian anaylses for 0.7

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#380]
hey @EJWagenmakers,

I propose to include log(BF) as an option alongside BF₁₀  and BF₀₁ in all Bayesian anaylses for 0.7

What do you think?

**Comment by EJWagenmakers** [comment]
Sure. So a general option to report logs then, so that BF10 becomes
log(BF10) and BF01 becomes log(BF01)
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
I think:

Bayes factor type
  [  ] BF₁₀
  [  ] BF₀₁
  [  ] log(BF)

because no-one would ever want or need log(BF₀₁)

**Comment by EJWagenmakers** [comment]
So what is the third option? BF stands for BF10? And why wouldn't people
want log(BF01)? Because it is usually not that big?

If all of this is correct, why not add the log option after the BF10? Right
now, just adding "log(BF)" is confusing
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
But in general, it is easiest/simplest to have a separate "log" operator
that affects *both* BF10 and BF01.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> So what is the third option? BF stands for BF10?

yup.

> And why wouldn't people want log(BF01)? Because it is usually not that big?

you want BF₀₁ because when BF₁₀ is less than one, it's difficult to interpret (and people can't do this in their head). but log(BF₁₀) doesn't have this problem - and if you did want to express it in favour of the null, people have no difficulty transforming -7 to 7, or vice versa

**Comment by EJWagenmakers** [comment]
I see your point now. But I'm not sure that the benefits outweigh the
drawbacks (more buttons, more confusion). I was confused initially as well.
You have to know, for instance, that -1 means evidence for H0 and +1 means
evidence for H1....
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
It's only one more button, and in general, if people don't understand an option, they won't tinker with it.

But this is a really easy concept to get, and really intuitive. We can add it in, and if no-one uses it, we can pull it out.

**Comment by EJWagenmakers** [comment]
Let's ask the others first.
E.J.


********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
I enthusiastically support this new option. A wonderful idea.
E.J.
