### ISSUE TITLE
B ANOVAs: Add support for BF₁₀, BF₀₁ and Log(BF) Bayes factor option

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#385]
hey @mmarsman1,

the UI is implemented and waiting!

no rush, 0.7 is not for at least 3 weeks

**Comment by mmarsman1** [comment]
Behave.

On 24 Feb 2015, at 21:48, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @mmarsman1<https://github.com/mmarsman1>,

the UI is implemented and waiting!

no rush, 0.7 is not for at least 3 weeks

**Comment by mmarsman1** [comment]
I currently implemented the change for the individual models in the model comparison, but I am reluctant to change BF_M, BF_Backward, BF_Forward and BF_Inclusion, since it becomes vague as to what that would mean to the user (or me).

We can invert BF_M and BF_Inclusion, but I am unsure what this would means. 
It is not possible to invert the individual components, since that does not constitute a proper Bayes factor I suppose.
The BF01 option would make BF_Forward; the null model vs the least complex model with the effect, and BF_Backward; the most complex model without the effect vs the most complex model with the effect.

What is your opinion on this @EJWagenmakers ?

If we do want to change them, we need to rename them so that it is clear what the option BF10 or BF01 does to them.

**Comment by EJWagenmakers** [comment]
We need to talk about this, because I am lacking some context. For
instance, in the first sentence, it is not clear to me what you mean with
"the change". Everything was perfect, and only the underlying code needed
to be cleaned up, right?
EJ

**Comment by mmarsman1** [comment]
"The change" is the new option BF01 instead of BF10. 

I just realised that I did make one change to the old version regarding BF_forward, we can discuss that.
