### ISSUE TITLE
Bayesian ANOVAs: Should we call nuisance terms, nuisance?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#394]
@EJWagenmakers, @mmarsman1 

i always thought that "nuisance" was a term that was coined in one of those papers, and so i didn't want to change it. but i now don't think this is the case.

is there a better name? or better way we can refer to this? 

*nuisance* isn't bad, and as a label it's a heck of a lot better than other labels people have to learn; *random factors* and *fixed factors* (which as labels, make zero sense)

**Comment by mmarsman1** [comment]
Nuisance is a common term to refer to parameters (or effects) that are part of the model, yet one is not (primarily) interested in. I agree with you that it may unfamiliar terminology for users. I can’t think of anything better though, and it is at least consistent with the literature.

Fixed and random factors, or fixed or random effects are problematic in the Bayesian paradigm, since everything is random. I do think that there is some common ground among researchers that they understand what is ment in saying fixed or random in this instance (although their distinction has more to do with their modelling assumptions than “randomness”).

On 26 Feb 2015, at 08:42, Jonathon Love <notifications@github.com<mailto:notifications@github.com>> wrote:


@EJWagenmakers<https://github.com/EJWagenmakers>, @mmarsman1<https://github.com/mmarsman1>

i always thought that "nuisance" was a term that was coined in one of those papers, and so i didn't want to change it. but i now don't think this isn't the case.

is there a better name? or better way we can refer to this?

nuisance isn't bad, and as a label it's a heck of a lot better than other labels people have to lean; random factors and fixed factors (which as labels, make zero sense)

**Comment by jonathon-love** [comment]
> Nuisance is a common term to refer to parameters (or effects) that are part of the model, yet one is not (primarily) interested in

oh, righto. in which case we totally shouldn't change it. i thought it was a term richard had invented.
