### ISSUE TITLE
Means with missing data

### ISSUE THREAD

**Issue by CJCarpenter** [jasp-stats/jasp-desktop#400]
I loaded a data file and it can give me distributions and correlations, but when I click on Descriptives and ask it for means, it give me nothing but white space. In the same file it will give me means when I use a variable with no missing data. Given this difference, I assume it is due to the missing data in the other variables that JASP will not provide means.

**Comment by jonathon-love** [comment]
hi,

means are produced only for continuous variables. i would guess that your variable which receives no mean, is a nominal variable (there should be a footnote which says "Not all values are available for nominal and ordinal variables").

if you look at the top of each column, you will see one of three symbols; three circles, three bars, or a ruler; these are nominal, ordinal and continuous variables respectively. no means are produced for nominal variables .

when you load in a data file, it uses a best guess to determine the variable type (same as SPSS).

if you want to change the variable type, you can click the small icon at the top of the column and this will bring up a menu (this is not the same as SPSS).

if you change the variable type from nominal to continuous, then descriptives should provide you with means.

let me know how you go!

jonathon

**Comment by CJCarpenter** [comment]
Hello Jonathan

Yes, telling JASP it was continuous did the trick. I'm not sure why it uploaded it as a nominal variable, but I'll know to keep an eye out for that in the future. 

Thanks for your prompt and effective help!

Chris

----- Original Message -----

**Comment by jonathon-love** [comment]
> I'm not sure why it uploaded it as a nominal variable

the criteria for something being considered continuous is:
 - all cells must contain a numeric value
 - there must be at least 24 unique values

i'm not sure where your dataset has come from, but if it was created using the `write.csv()` command in R, then this would cause issues. `write.csv()` has a bug... err, i mean feature... where missing values are replaced with `NA`. `NA` is a string, and so the column gets treated as nominal.

of course, this is fixed by changing the column to continuous; all non-numeric values are converted to missing values (including the NAs), and so you end up with an equivalent dataset to what was in R.

**Comment by CJCarpenter** [comment]
I think the problem stemmed from there being less than 24 unique values. I had a 7-pt likert scale so there were only 7 unique values.

----- Original Message -----

**Comment by jonathon-love** [comment]
> I had a 7-pt likert scale so there were only 7 unique values.

then that's definitely a categorical variable, and you certainly shouldn't be reporting means! :P
