### ISSUE TITLE
B 1S T-Test: Large variability in results

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#417]
hi @EJWagenmakers, @quentingronau 

see the following screenshot. i have four identical analyses, and they produce wildly differing results.

![screen shot 2015-03-04 at 6 01 06 pm](https://cloud.githubusercontent.com/assets/3240247/6488552/8ec1b360-c298-11e4-8784-eb5d822fc5d0.png)

**Comment by jonathon-love** [comment]
hmm, if you remove the ssd variable, you don't get any result for rt

![screen shot 2015-03-04 at 6 06 19 pm](https://cloud.githubusercontent.com/assets/3240247/6488662/3ecc6a7a-c299-11e4-82be-4d8981e34e66.png)

**Comment by EJWagenmakers** [comment]
Hmm. I'll take a look. What example data set is this? And where on my
computer can I find the latest version of JASP that you just installed?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
The result might be too extreme.
Have you tried with a variable that is near zero?
EJ

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> What example data set is this?

ssgo-fred.csv, i'll email you

> And where on my computer can I find the latest version of JASP that you just installed?

so i didn't install it, but i updated your source version. to run it, you'll need to open Qt Creator, select JASP under recent projects, and then click the play button in the lower left.

> The result might be too extreme.

yeah, i think so.

> Have you tried with a variable that is near zero?

of course not, i expect that will work :P

**Comment by EJWagenmakers** [comment]
OK, I am looking at this now.
Has this been fixed? I just get the same result, which is plausible, namely
overwhelming evidence against the null. See attached screenshot.
Cheers,
E.J.


********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> See attached screenshot.

ooh, in order for us to get the screenshot, you'll have to add it through the github issue page.

(this also means we don't get all the signature shite)

**Comment by jonathon-love** [comment]
i'm guessing that you can't reproduce this for one of two reasons:

1. this is an issue with the t-distribution estimation, only affects the 0.6.5, and you are running 0.6 (did you use QtCreator to launch it?)
2. you're not choosing one-sided

**Comment by quentingronau** [comment]
I updated yesterday the fitting of the t distribution due to another issue. Now, the unrestriced test for rt yields Inf (as was always the case, if I remember correctly), and the left- and right-sided test yield NaN because they are computed using BF10 which is Inf. To be honest, I do not now why a result was produced before my update. I need to think of a sensible error message, something like: "BF10 is Inf, no order-restricted tests possible". Maybe you have a better suggestion for this error message.

**Comment by quentingronau** [comment]
Also, when I will have implemented Richard's suggestion to use logs, the threshold where this procedure fails, might increase.

**Comment by jonathon-love** [comment]
> I need to think of a sensible error message, something like: "BF10 is Inf, no order-restricted tests possible"

if BF10 is infinite, then the BF for one sided tests will either be Infinite or zero? Can we determine which and just display this?

**Comment by jonathon-love** [comment]
@EJWagenmakers,

> i'm guessing that you can't reproduce this for one of two reasons:

*3*. you haven't checked "exclude cases listwise"

**Comment by EJWagenmakers** [comment]
Jonathon is spot-on with his solution! The sign of observed effect size
tells us which one-sided test is inf and which one is 0.

Now it may be that, after this has been fixed, we can stil run into trouble
when BF10 is *almost* infinite. Then the area to one side of zero may be do
small that the t-distribution doesn"t work for yhe one-sided cases. You'd
have to carefully construct this situation, but I am confident that
Jonathon will succeed :-)

EJ

**Comment by jonathon-love** [comment]
but we still need to figure out the wildly differing results

**Comment by EJWagenmakers** [comment]
I'll take a look.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
OK, I looked more carefully now. A few weird things are going on. Here's a
list of issues and suggestions:

1. For the one-sided tests (both for the tables and when a plot cannot be
produced), we now produce the error message "non-finite finite difference
value [2]". This is too cryptic. What I suspect is that the posterior mass
< 0 is almost zero. So that means the BF is too extreme. This would be a
more informative error message (if this is what's going on). Also, even
when we cannot determine that area, we can still plot the posterior
distribution, right?

2.In Jonathon's example, the test on ssd gives a NaN. The BF-0 for rt is
highly variable. My take on this:

First, I looked at the case of the regular two-sided test. This already
produces a puzzling result. When I test *both* rt and ssd, I get large
positive BFs. When I test *only* rt, I get infinity! (this is
systematically the case). So it appears there is some dependency between
the tests, which I don't understand at all. What is going on?

Second, right now we don't plot the posterior distribution when the BF is
infinite. I assume this is because we don't get any samples from the
BayesFactor package in that case? (just checking)

Third, when the BF is NaN, the error % cell should be blank (i.e., remove
the \approx sign).

Fourth, I then tried BF-0. First, the plot for rt remains empty even though
it gives BF=23.61. And yes, the outcome is variable. What happens here is
that BF_10 is HUGE, and the posterior proportion below 0 is TINY. The
procedure then needs to multiply HUGE by TINY, and very, very small
numerical errors in estimating "TINY" will give different end results. We
may not be able to resolve the issue because we are faced with limitations
of computer precision and speed.

What we can do is check whether BF+0 is almost twice BF10. When it is very
close (in terms of a percentage) and the user wants to know BF-0, we can
(1) up the number of samples from the posterior used to estimate the
t-distribution [or normal, as per Richard's suggestion], in order to obtain
more reliable results ; (2) indicate in a table footnote that the estimate
is unreliable because the effect is strongly in the other direction.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> So it appears there is some dependency between the tests, which I don't understand at all.

the "exclude missing values listwise" is responsible for the dependency.

> What happens here is that BF_10 is HUGE, and the posterior proportion below 0 is TINY. The procedure then needs to multiply HUGE by TINY, and very, very small numerical errors in estimating "TINY"

this wouldn't be solved by calculating the other tail, and subtracting it from 2*BF10 ?

**Comment by jonathon-love** [comment]
> Third, when the BF is NaN, the error % cell should be blank (i.e., remove the \approx sign).

i'll handle this

**Comment by EJWagenmakers** [comment]
Hi Jonathon,

> So it appears there is some dependency between the tests, which I don't
> understand at all.
>
> the "exclude missing values listwise" is responsible for the dependency.
>

Ahhhh I see! Good.


>  What happens here is that BF_10 is HUGE, and the posterior proportion
> below 0 is TINY. The procedure then needs to multiply HUGE by TINY, and
> very, very small numerical errors in estimating "TINY"
>
> this wouldn't be solved by calculating the other tail, and subtracting it
> from 2*BF10 ?
>
Unfortunately, no.

E.J.

**Comment by jonathon-love** [comment]
i am left with some serious doubts about this error % calculation

**Comment by EJWagenmakers** [comment]
That's true, at least in some situations. When the posterior mass becomes
tiny, very small estimation errors may result in huge fluctuations. But
*only* if you test the hypothesis that is inconsistent with the direction
of the effect! So we should detect this situation (as I outlined in the
previous mail) and replace the % calculation with a warning.

Also, it may be better to replace the \approx sign with a single wavy line,
a tilde ~. This indicates an approximation that is more rough.

Cheers,
 E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> But *only* if you test the hypothesis that is inconsistent with the direction of the effect!

so the error calculation itself has an error

> Also, it may be better to replace the \approx sign with a single wavy line, a tilde ~. This indicates an approximation that is more rough.

righto

**Comment by EJWagenmakers** [comment]
Well we assumed the fit of the t-distribution is very good so that the
error is negligible. But that is not true if you are out all the way in the
tail of the distribution (on the one side).

So when computing a one-sided test, let's just check whether 2*BF10 is
within 1% of the "correct restriction" hypothesis.(alternatively, we can
estimate whether the posterior proportion greater or smaller than zero >.99
or something) If so, and if the required test then concerns the "incorrect
restriction hypothesis", then we should issue a warning.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by quentingronau** [comment]
I changed some things concerning the fitting procedure.  "non-finite finite difference
value [2]" is an error in the optim function and occurs if there are problems computing the gradient. I now use another method if "BFGS" fails, which does not rely on evaluating the gradient (i.e., Nelder-Mead) and I use another sigma starting value, i.e., 0.01, if N is extremely large so that 1/N is not an appropriate starting value anymore. This should take care that  the error message does not occur anymore (at least I hope so), and the plots should be appropriately displayed.

Wrt:
"Second, right now we don't plot the posterior distribution when the BF is
infinite. I assume this is because we don't get any samples from the
BayesFactor package in that case?"

The BayesFactor package does produce samples for BF=Inf (at least for the cases I tried). Shall I enable plotting for such cases? (I was just not sure if a plot should be produced if BF=Inf).

"Fourth, I then tried BF-0. First, the plot for rt remains empty even though
it gives BF=23.61."
Now a plot should be produced.

**Comment by jonathon-love** [comment]
> The BayesFactor package does produce samples for BF=Inf (at least for the cases I tried). Shall I enable plotting for such cases?

in this situation the BayesFactor is only Infinite when converted to the normal scale (it's not infinite on the log scale). i'm going to add a special formatter which will translate the result from the log scale to a string at the very last stage. by manually taking over this process, we can handle values which would otherwise be continued Infinite.

so you can still plot these, and i will come up with a log renderer soonish.
