### ISSUE TITLE
B-correlation plot (placing rho a bit lower beneath the x-axis)

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#473]
The symbol rho is really close to the x-axis-labels:
 
![screen shot 2015-03-12 at 15 49 02](https://cloud.githubusercontent.com/assets/8667548/6620053/d7c9e67c-c8ce-11e4-8c3a-7ee110a285c2.png)

**Comment by quentingronau** [comment]
Hi @mmarsman1,

I agree, I should change that. Can you maybe send me a screenshot how you produced that?
When I use the matrix plot, it looks like this:

![rhotoclose](https://cloud.githubusercontent.com/assets/8697436/6623396/f68145c4-c8e2-11e4-8c9a-e2512a232ee1.png)

**Comment by mmarsman1** [comment]
Of course :)

![screen shot 2015-03-12 at 20 43 55](https://cloud.githubusercontent.com/assets/8667548/6626578/28e2208c-c8f8-11e4-9b7e-b4f651cde63c.png)

![screen shot 2015-03-12 at 20 43 45](https://cloud.githubusercontent.com/assets/8667548/6626584/2c1464f4-c8f8-11e4-997a-87c3e1fee52e.png)

**Comment by quentingronau** [comment]
@mmarsman1: Hm, that is peculiar, on my computer it looks like this. I changed the position of the rho x-label one or two weeks ago, but I am sure you have done a rebase since then.

@jonathon-love : Do you have an idea what the reason might be?

![issue473](https://cloud.githubusercontent.com/assets/8697436/6655312/22727c5c-cafa-11e4-9ede-42b8ac9ecdf4.png)

**Comment by jonathon-love** [comment]
looks like a font issue. @quentingronau is running windows, and @mmarsman1 is running osx. R will use slightly different fonts on different OS'es. the best you can do is pick spacing that looks OK on both.
