### ISSUE TITLE
Distinguishing groups in the Bayesian contingency table

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#475]
@Tahiraj , @jonathon-love 
In the Bayesian contingency table, for the independent multinomial in the 2x2 case (i.e., comparison of two proportions) there is the option to test one-sided: group 1 > group 2. But how can I know which group is which?
Example as screenshot.
![image](https://cloud.githubusercontent.com/assets/8603015/6622119/df62c118-c8da-11e4-8128-60313fb53450.png)

**Comment by Tahiraj** [comment]
@EJWagenmakers @jonathon-love 
![screenshot 2015-03-13 16 24 34](https://cloud.githubusercontent.com/assets/9108433/6641485/4c2fd524-c99e-11e4-9034-33c8b9bb53c6.png)

**Comment by jonathon-love** [comment]
i would take a look at the t-tests. there we put the groups in the footnote.

**Comment by Tahiraj** [comment]
In t-test the groups are variables names. Here the groups are levels of row or column name. I have not commit yet.

**Comment by jonathon-love** [comment]
hi, in the independent samples t-test, the groups are levels, see below. having said that, i think the footnote isn't so critical in the contingency tables, because the contingency table (above) list the groups in order. but the footnote would nice so as to be consistent.

![screen shot 2015-03-13 at 5 29 02 pm](https://cloud.githubusercontent.com/assets/3240247/6642654/783ee314-c9a6-11e4-97e7-8edb59486fe5.png)

**Comment by EJWagenmakers** [comment]
But I am not sure the order of display in the contingency tables is
correct. Is group 1 really the top group? I don't think so
EJ

**Comment by Tahiraj** [comment]
what do you mean by "Is group 1 really the top group". Now we have also options to reverse the order of groups in Contingency table.

**Comment by EJWagenmakers** [comment]
The order-restrictions allow one to select "group 1 > group 2". However,
with rows fixed in a 2x2 table, group 1 does not always correspond to the
top row. I can show you on Monday.
EJ

**Comment by Tahiraj** [comment]
Ok!
