### ISSUE TITLE
Some general observations regarding moderate no. observations in analyses.

### ISSUE THREAD

**Issue by mmarsman1** [jasp-stats/jasp-desktop#489]
@jonathon-love @EJWagenmakers 
So, as can be seen from some bug reports I did some analyses with a moderately large n (10,000) this evening, which reads as huge when you work in a psychology department, but not outside that department :)

Plots take really - really - long to compute; also simple scatterplots and histograms.
Perhaps in the latter there is some kernel - density - estimation stuff that takes so long?

Bayesian correlations are faster than regular correlations. 
Kudos @AlexanderLyNL !
Also important to note is that the function does NOT terminate when n is moderately large and r is high (either 1 or 0.995).

Outside of some specific model BF-issues and the above, Jasp did perform well :)

**Comment by EJWagenmakers** [comment]
Thanks for looking into this so carefully! Great that the correlations are
doing so well. Yes I bet the kernel density estimation slows things down.
For the descriptives, do we use polspline or density? The latter is faster
in my experience.
EJ

**Comment by AlexanderLyNL** [comment]
I didn’t do much computationally. The kudos are mostly for Robin Hankin, 

http://cran.r-project.org/web/packages/hypergeo/hypergeo.pdf

but the truth of the matter is, that to produce a Bayes factor BF10:

For r=0.6
1. the exact BF10 is infinite whenever n > 3170 
2. the Jeffreys integration BF10 is infinite whenever n > 3170 
3. the numerical Jeffreys integration BF10 is infinite whenever n > 815 (so it’s actually useless to calculate a Bayes factor based on the “integral” function in r) [Hence, for greater efficiency I should take this one out]
4. the Jeffreys approximation BF10 is infinite whenever n > 3201 (this Bayes factor does not even produce one-sided Bayes factors). 

For r=0.8
1. the exact BF10 is infinite whenever n > 1388
2. the Jeffreys integration BF10 is infinite whenever n > 1388
3. the numerical Jeffreys integration BF10 is infinite whenever n > 464 
4. the Jeffreys approximation BF10 is infinite whenever n > 1400 

Conclusion
1. Not too many irrelevant calculations: Fortunately, my Bayesian correlation suite does not do too much irrelevant calculation (they produce infinities anyways). Furthermore, the hypergeometric function in R is quite okay, that is, (hypergeo::genhypergeo which is superior to hypergeo::hypergeo)
2. No difference in the two hypergeometric methods: The second method (Jeffreys integration BF10 [aka the bathing BF10, aka EJ’s BF10) has the same bound as the exact one (both use the hypergeometric function)
3. Numerical integration is useless: The use of “integrate” in R is rather useless. Hence, for greater efficiency I should take this numerical integrate version out of my BF suit.
4. Even a crude limit theorem exhausts R: Jeffreys approximation BF10 is the one Jeffreys actually reports, a BF10 that is based on normality. For this method I do not even have one-sided Bayes factors. Furthermore, note that the threshold of this Bayes factor is only a bit higher than the ones we get for the Bayes factors calculated with the hypergeometric function which actually does produce one-sided Bayes factors as well. Hence, this confirms the observation that the exact BF10 and the EJ BF10 are not too bad and that the hypergeometric function in R performs well. 
5. Hitting R’s overflow bound: Based on the observation 

> .bf10Exact(n=1388, r=.8)
[1] 3.684325e+305

> .bf10JeffreysApprox(n=1400, r=.8)
[1] 1.682996e+308

and

> 10^309
[1] Inf

I think that we have reached R’s limit. 
6. Sampling is useless: This brings us back to the discussion of implementing a sampler. To recap, to calculate the area under the curve of the posterior we hit a bound when n=1388, r=.8 due to the fact that we get an extremely high number 10^305. We can draw a posterior up to n=1365, r=.8 (that is, a beta approximation posterior). I don’t see the merit in writing a sampler that does not improve much on the exact results. I would still like to write a sampler, but then for something that is useful, for instance, Marsman’s sampler in JAGS using a convolution for the exGauss.

**Comment by EJWagenmakers** [comment]
There are two issues: computing the BF and plotting the posterior. I am
perfectly content with reporting infinity or zero once the BF results
exceed the numerical limits or R.

However, there should be a plot if the posterior even when it is located
far away from zero. So I like to use the sampler not for model selection
but for parameter estimation.

EJ

**Comment by AlexanderLyNL** [comment]
Which priors would you like to use for estimation? The testing priors are the Jeffreys priors on the nuisance parameters and uniform on rho. I guess that you would like to do the same for estimation. In fact, Jeffreys estimation priors are the same as his model selection priors. 

This means that what holds for the Bayes factor also holds for the estimation problem. More specifically, BF10 is exactly the normalisation constant of the posterior (see, our Jeffreys paper). Hence, I can give you the posterior for rho based on the functions I have, that is, I can plot a beta approximation of the posterior for r=0.8 and n=1365. Furthermore, I can also give you the credible intervals for r=0.8 and n=1365, but not beyond that.

The previous post shows that: 
1. You can only get the normalisation constant of the posterior for r=0.8, n=1388, simply because R cannot handle larger numbers. 
2. What’s the merit in writing a sampler that allows you to plot 23 more posteriors at best? 
3. We’re hitting R’s largest number. There are three solutions: (a) Write a new statistical software package and drop R out of JASP, or increase its largest number. (b) plot unnormalised posteriors, but then again, you can plot anything then, because it doesn’t really matter anyways. (c) Plot a normal distribution a la Fisher, due to the Bernstein-von Mises theorem.

**Comment by EJWagenmakers** [comment]
Yes, same priors for estimation. When we program the sampler we don't need
the normalization constant. I think we can work it out.
EJ

**Comment by EJWagenmakers** [comment]
To reiterate, it is not really a problem if R hits its numerical limit: the
hypothesis test shows a clear result (we should return 0 or infinity in
these cases?).

But it is a problem if we can't plot the posteriors because they happen to
be far from 0. And we can fix that, I think, because drawing samples can be
done without the normalization constant.

EJ

**Comment by EJWagenmakers** [comment]
As a (suboptimal) solution, JAGS would allow you to obtain samples from the
posterior at will. Of course, we cannot yet use JAGS functionality in JASP,
but this would be an example where it comes in handy.
EJ
