### ISSUE TITLE
B PS T-Test: doesn't always analyse all requested pairs

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#502]
if the user specifies the same pair twice, it only appears once in the results table.

i can see where you're coming from, but often its just simpler, and causes less confusion, if you just give the user exactly what they request.

**Comment by quentingronau** [comment]
Hi @jonathon-love, 

Maybe I am wrong, but I think if the user selects the same pair twice, the pair just shows up once in options$pairs, which is the reason for only appearing once in the results table because I loop over options$pairs. Do you have a suggestion how I can fix that?

![issue502](https://cloud.githubusercontent.com/assets/8697436/6675543/6b73c01e-cc21-11e4-9ebf-3589773f127d.png)

**Comment by jonathon-love** [comment]
you are completely right. i'll take care of this.

**Comment by quentingronau** [comment]
Thanks
