### ISSUE TITLE
B Cont. Tables: Q about posterior

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#519]
hi @Tahiraj, @EJWagenmakers 

i just wanted to double check this is correct. for the following, we're doing a one-sided test. in the t-tests, this leads to the truncation above or below zero. i appreciate this is different, but just wanted to double-check that this shouldn't be truncated in some way.

![screen shot 2015-03-18 at 3 17 41 pm](https://cloud.githubusercontent.com/assets/3240247/6710606/29f8f700-cd82-11e4-99d3-50e96fbe9fe0.png)

**Comment by EJWagenmakers** [comment]
Good point. It is not a big issue and we don't need to fix it before the
release, but I think it should be truncated, just like the t-test.

Also, maybe we can change the label on the x-axis to read Log(odds ratio)
instead of the current log(Odds ratio) -- this way, the label is consistent
with the capitalization in the input field.

E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by Tahiraj** [comment]
I think odds ratio is different from t-test so it should not be truncated above or below zero. Anyway I’ll look into it. 
Tahira

**Comment by Tahiraj** [comment]
Odds ratio indicating evidence of association between the row variable and column variable. Whereas the one sided restricted test is between the levels of a groups of row or column. 

Now the x-axis is labeled as Log(odds ratio).

**Comment by EJWagenmakers** [comment]
I'm not so sure. If you test one-sided, do high BF+0 (e.g., 100) correspond
to positive log odds, and high BF0+ (e.g., 100) correspond to negative log
odds?
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by Tahiraj** [comment]
Ok, Let me explore then we’ll discuss.
Tahira

**Comment by jonathon-love** [comment]
did we have a resolution for this?

**Comment by EJWagenmakers** [comment]
No resolution yet. Let's discuss this with the others too.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by Tahiraj** [comment]
This issue has been fixed in 0.7. 

Tahira
