### ISSUE TITLE
JASP binaries.

### ISSUE THREAD

**Issue by DavidParkin** [jasp-stats/jasp-desktop#532]
Are there any 32 bit binaries for Linux and/or are there any instructions on how to compile, make files, for instance?

**Comment by jonathon-love** [comment]
hi, we don't provide 32-bit binaries for linux sorry (it's difficult to support every architecture, OS combo, and we have limited resources)

JASP is most easily built using Qt Creator. we have info on what you'll need to build it here:

https://github.com/jasp-stats/jasp-desktop/

building it yourself for linux is quite an undertaking, due to the number of R packages, etc. required. that page also has a document listing the R packages you'll need.

honestly, it's probably easier to upgrade yourself to 64-bit ubuntu.

all the best

jonathon

**Comment by DavidParkin** [comment]
Thanks,
* My first problem was that I am not that familiar with Qt and had an old version of Creator. Updated. 
* Fetched some packages from CRAN into my installed R and copied the 32 bit binaries over the 64 bit binaries. 
* Copied libR.so and it compiled no problems. Some simple tests have shown no problems.

David

**Comment by jonathon-love** [comment]
hey! great work! :)

here's the complete R package list:

https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-r-packages-list.md

**Comment by jonathon-love** [comment]
hey! there's 32-bit binaries of JASP now available from our PPA

https://launchpad.net/~jonathon-love/+archive/ubuntu/jasp
