### ISSUE TITLE
B ANOVAs: Proposal to make analysis of effects the default

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#614]
hi @EJWagenmakers,

@mmarsman1, @raviselker and i are thinking (with varying levels of conviction) that the /analysis of effects/ table should be the default output for the Bayesian ANOVAs, and the model comparison should be an option.

i think the two motivations are:
 - with 3 terms the model comparison is hard to read, with four or more it's impossible (and the user has to scroll 5 pages down to the /analysis of effects/ table which is still readable.
 - /analysis of effects/ is more analogous to a classical ANOVA.

this may not be a great forum to discuss, but we've been murmuring about it for a while, and so i thought we should get the ball rolling.

**Comment by EJWagenmakers** [comment]
Yeah I see the point. I have no strong preference.
EJ

**Comment by jonathon-love** [comment]
thinking about it, i now have some doubts about analysis of effects. take the following for example:

![screen shot 2015-05-24 at 8 44 25 pm](https://cloud.githubusercontent.com/assets/3240247/7789114/beccfaa4-0255-11e5-8d21-9ec668eb9e98.png)

depending on what we mark as nuisance, the analysis of effects can find evidence both for and against a particular term (in this case, the disgust * fright interaction).

in the first case, the fact that the model comparison contains the highly implausible intercept only model, inflates support for the model containing the interaction; which is misleading (or wrong?)

**Comment by EJWagenmakers** [comment]
When you average across models (as you do in the effects analysis), the
results will depend on what models you include. You could ignore the
intercept-only model, but even then the (small) "inconsistency" can arise
(for instance, in your example, "disgust" only is very unlikely).

Actually, this is a good opportunity for a question; for these data, do you
think there is evidence for "disgust"? The tables give three answers:
1. Yes, BF_10 = 20.9
2. Yes, BF_inclusion = 46.8
3. No, P(M|data) = 4.5 E-9

This is not inconsistent -- these are answers to slightly different
questions. From a consideration of all the evidence, it is apparent that
the best model requires both disgust *and* fright, and including the
interaction does not do much. This is also why I feel that including more
information is useful, because focusing on any one answer is dangerous. I
guess we'll just have to go over a series of examples, and see what is most
useful in practice. I think the effects analysis will become more useful as
the number of predictors increases and the models are about equally good.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
> This is also why I feel that including more information is useful, because focusing on any one answer is dangerous

but in your example, i think you can reach the same conclusion about the importance of frighteningness *and* disgustingness from the BF10 column alone.

> I guess we'll just have to go over a series of examples, and see what is most useful in practice.

yeah, totally.

> I think the effects analysis will become more useful as the number of predictors increases and the models are about equally good.

yeah, totally. especially with the RM ANOVAs.

but i'm currently feeling as though analysis of effects should not be the default (and the model comparison should be the default, as we currently have it). the BF10 column of the model comparison table, although at times unwieldy, is the easiest to interpret, and is never deceptive (that i can see).

**Comment by EJWagenmakers** [comment]
We need more experience before making decisions. The question about the
main effect of disgust is answered by the BF10 column only indirectly; at
lesst that's how I feel. My advice is to keep everything the same for now.
In the near future we will add functionality from the conting package and
perhaps this gives new insights and constraints.
EJ

**Comment by EJWagenmakers** [comment]
Plus there are a few addition things about the anova interface that we
should discuss.
EJ

**Comment by jonathon-love** [comment]
yeah, at this point i feel like we're more discussing issue #633 more than this one, but:

> We need more experience before making decisions.

yeah, that's my motivation. i'd like to bring things back to something closer to a blank slate, which then we can add values to as we find them to be useful.

it's not so much that i want to make decisions, but i want to undo [potentially unprincipled] decisions from the past - and then make good decisions about what to add.

i keep bringing this up, because this becomes more acute as publications draw near. we risk either having to change things down the track, undermining our pubs, or being compelled to keep unnecessary values which clutter the UI (like SPSS' results), so as to remain consistent with our pubs.

we can always add things, but taking away is always problematic.

> The question about the main effect of disgust is answered by the BF10 column only indirectly

yeah i agree, but the other values are even less direct (as far as i can tell).

**Comment by EJWagenmakers** [comment]
Yeah let's stick to what we had in the previous release and make decisions
later.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
Trust me on this one.
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by jonathon-love** [comment]
i think we're agreed that *analysis of effects* should not be made the default.

**Comment by EJWagenmakers** [comment]
Yes, agreed

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************
