### ISSUE TITLE
Add footnote facility for plots

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#720]
hey @quentingronau 

i think the descriptives matrix plot should plot _Nominal_ and _Ordinal_ variables too (but obviously, not _Nominal Text_). we try to make it so that the user doesn't have to interact with the type system if they don't want to - and they could be puzzled why these aren't showing up.

also, i think it should plot variables with infinities too (just exclude them); at the moment, i think the user would be similarly puzzled as to why these aren't showing up.

when done, i'll assign this issue to dora so she can update the help system.

cheers!

**Comment by jonathon-love** [comment]
also, you could put a space after the commas in the matrix heading.

i.e.

    block,trialNo,bruce

could become

    block, trialNo, bruce

or you could just drop the heading altogether. these labels appear across the top of the plot anyway.

**Comment by quentingronau** [comment]
Hi,

"the descriptives matrix plot should plot Nominal and Ordinal variables too (but obviously, not Nominal Text)"

I am just not sure whether it is reasonable to present the user with the scatterplots for these cases. In particular, the line that is drawn is not really meaningful if the variables are not continuous, I think, but maybe I am wrong.

Furthermore, I think the marginal distributions (diagonal elements of the plot) for these cases should be barplots instead of histograms.

Maybe we should ask someone else for an opinion about that, maybe E.J.?

Cheers,
Quentin

**Comment by jonathon-love** [comment]
actually, lets not plot them, and put a note in a footnote.
