### ISSUE TITLE
B Corr Pairs: Are the savage dickey dots in the right place?

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#740]
oh wait, has the beta prior width been properly implemented yet? because it isn't enabled.

![screen shot 2015-06-20 at 10 27 21 am](https://cloud.githubusercontent.com/assets/3240247/8266595/2dac5fe6-1737-11e5-96f5-ed04eeb7980e.png)

**Comment by quentingronau** [comment]
The point for the posterior is not in the right place, it should be exactly on the line. I think this is because I sometimes switch to the beta approximation if the normal posterior function does not work.
I will try to fix it, but I do not have an example to test, so please let me know if it is fixed. Apart from that, the prior width should be properly implemented I think.

**Comment by quentingronau** [comment]
I just saw your mail with the data, for me it works now.

**Comment by jonathon-love** [comment]
so i can enable all those options?

**Comment by quentingronau** [comment]
All options can be enabled, I think, except the Sequential Analysis Robustness Check tick box, because clicking this yields at the moment the same plot as Sequential analysis alone.
