### ISSUE TITLE
Font size for help system too small?

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#752]
Maybe it is my computer again, but I found this text a little hard to read. Also, I wonder whether we should give the help function more room on the screen. Right now the user will almost always have to resize it to read the text.
![image](https://cloud.githubusercontent.com/assets/8603015/8303176/6110fd8a-199c-11e5-9b3d-dc6151bac1b9.png)

**Comment by EJWagenmakers** [comment]
(in the above screenshot I already resized it to what I think is reasonable). Hey, it is awesome that the system remembers the resize, so the user only needs to do this once!
E.J.

**Comment by jonathon-love** [comment]
the help starts out deliberately narrow, because otherwise on smaller screens it completely obscures the output panel, and i'm concerned the user wouldn't know what was going on ("where has the output gone?")

then it remembers to where the user sizes it, so it only needs to be done once.

as for font-size, we need to source a computer with similar font issues to yours so we can find a way to handle hi-res screens.

**Comment by jonathon-love** [comment]
hmm, looking again, i agree font-size could be a bit larger for help. i've bumped it up slightly.

**Comment by jonathon-love** [comment]
this change should take affect in the beta 4 or later
