### ISSUE TITLE
Hide prior width option in B Lin Reg UI

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#753]
In Bayesian regression, there is a box that sets the Cauchy prior width to 0.5. Is this the BayesFactor default? Also, it appears to be inactive.
![image](https://cloud.githubusercontent.com/assets/8603015/8303267/0b3d5c5e-199d-11e5-9f68-905d7ca99b3d.png)

**Comment by jonathon-love** [comment]
where we at with this @mmarsman1 ?

i thought i was to leave the prior width option in for regression, did i misunderstand?

**Comment by mmarsman1** [comment]
No, my understanding was that we removed all atm, since any change here (or other lms) affects behavior of all of them.

M

Verzonden van mijn HTC

----- Reply message -----
Van: "Jonathon Love" <notifications@github.com>
Aan: "jasp-stats/jasp-desktop" <jasp-desktop@noreply.github.com>
CC: "Marsman, Maarten" <M.Marsman@uva.nl>
Onderwerp: [jasp-desktop] Cauchy prior width in regression (inactive?) (#753)
Datum: di, jun. 23, 2015 16:32


where we at with this @mmarsman1<https://github.com/mmarsman1> ?

i thought i was to leave the prior width option in for regression, did i misunderstand?

**Comment by jonathon-love** [comment]
ok, i will remove.
