### ISSUE TITLE
Copy menu tweaks

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#769]
can this disappear when the menu is dimissed? this occurs when you bring up the menu, and then click somewhere else.

<img width="1324" alt="screen shot 2015-07-06 at 10 09 23 pm" src="https://cloud.githubusercontent.com/assets/3240247/8537357/bbd162e8-242b-11e5-8961-9b4e3f7826ad.png">

**Comment by jonathon-love** [comment]
1. one thing is that when selecting a menu for an individual item (i.e. a table); it highlights the whole item; where as selecting a menu for a whole analysis only highlights a border. what do you think about making these consistent?

2. in the scenario that a person has analysis 1 selected (highlighted in white), and then clicks a menu on analysis 2, should it unselect analysis 1?

3. should the drop down menu arrows only appear when the mouse cursor is over the heading? (rather than when over the table, or over the analysis) moving the mouse cursor around results in a lot of movement, and i find it a bit distracting. i think it will still be pretty discoverable. what do you think?

4. should there be a slight delay (or fade-in) between the dismissal of the menu (when a person clicks an item), and the appearance of the "Copied to clipboard" notification? the instant-ness of it makes it a bit harder for the eye to track.

5. what if we try making the drop down menu X position centered on the mouse cursor? i think the Y-position is spot-on, but maybe centering the X on the cursor would be good (i appreciate that positioning the X where it now is, was my idea)

6. i might experiment with making the drop down arrows a bit more subtle

thoughts?

**Comment by dropmann** [comment]
1. Fixed. It is because when the analysis is selected, the selected colour is white overriding the other colour. I changed it so the white is not applied when the analysis menu is selected.

2. The old code specifically stops an analysis from being selected when clicking the copy or cite buttons. Also clicking an already selected analysis causes it to be unselected. In light of this I have made it so that the analysis selects when the menu is clicked but doesn't deselect when a menu is clicked, while maintaining the deselect on a regular analysis click, except when clicking a menu away. It's a bit tricky but i think it works good.

3. i don't really mind. I don't mind the one or two extra hinting icons appearing, but i appreciate the potential cluttered look. Making the arrows more subtle might solve both problems.

4. I added the short delay and fade and it does look better.

5. Do tomorrow

6. Sounds good.

I'll commit this all tomorrow.

**Comment by jonathon-love** [comment]
1.awesome

2.

> The old code specifically stops an analysis from being selected when clicking the copy or cite buttons.

so i think i like this old behaviour.

> In light of this I have made it so that the analysis selects when the menu is clicked

i'm not sure about this though. i was originally meaning that if analysis 2 has been previously selected, and a menu of analysis 1 is clicked, analysis 2 becomes unselected. if i understand correctly, you're going one step further and additionally selecting analysis 1. i don't think we want to do that. for example, a person may have performed all the analyses, and may be adding commentary, etc. they may not want to be interacting with the options, etc. indeed, when no analysis is selected, you can have the results area resized much larger, etc. does that make sense?

> while maintaining the deselect on a regular analysis click

yeah, i love that deselect :)

'3. do you want to try it?

'4. awesome!

'5. awesome!

'6. awesome!

**Comment by dropmann** [comment]
In regards to point 2:

Previous behaviour (at least over here) - if analysis 1 is selected and i click the menu of analysis 2, analysis 1 remains selected. This maybe a windows thing. It did surprise me that this was happening. Initially i thought you wanted analysis 2 to become selected so that's what i changed it to yesterday. I understand the reason behind why that misunderstanding is not a great idea. I have changed it back to the way it was, however, it sounds like  your version has different behaviour which might be possible as mine is not doing what i expected in one area which allows for mine to work. I've added a catch that should fix yours as well.

**Comment by jonathon-love** [comment]
'3. i had a quick look at implementing 3, but it's probably easier for you

'6. i've done this now, what do you think?

'7. the clickable area for the table headings is narrower than the analysis headings, or the image headings. could the clickable area be made consistent? (i think i like the wide, but whatever)

'8. the positioning of the image headings isn't quite right (a bit high), see trialType below:

<img width="414" alt="screen shot 2015-07-09 at 6 21 58 pm" src="https://cloud.githubusercontent.com/assets/3240247/8608291/6a7707f2-2667-11e5-8abb-47b634bd0430.png">

**Comment by dropmann** [comment]
7. By narrower do you mean not as wide or tall?

**Comment by dropmann** [comment]
i answered the above question myself.... wide

**Comment by jonathon-love** [comment]
:)

**Comment by jonathon-love** [comment]
'9. do you want to exclude the "left-squash" column (the right most column) from the export of tables too?

**Comment by dropmann** [comment]
have done 8. and 9. looking into 3 now.

**Comment by dropmann** [comment]
3. is far more complicated. I tried it so the icon only appeared when the mouse was over the heading area. This was crap. Far to fleeting an event to even see it happen. Interestingly enough, even though i knew where the menus were i had trouble finding them because there is so much text navigate. The next option is to make the icon appear when the mouse is exclusively over an item (ie image, table or analysis) but this is proving to be difficult... at least for me. When you are over one you are also over the other. I'll keep trying to figure it out but it might take some time. If you have any ideas let me know. 
My feeling at the moment is that the current behaviour is the nicest because of the amount of text and labels it very easily just shows you where they are.

**Comment by jonathon-love** [comment]
yeah, righto. whatever you think is best.
