### ISSUE TITLE
Bayesian Anova: BF values changes

### ISSUE THREAD

**Issue by MarioDalmaso** [jasp-stats/jasp-desktop#774]
Hi,

I have conducted a Bayesian Anova with JASP 0.7. I have noticed that output values (BF etc.) change when I simply change the names of the factor/level.

Cheers,
Mario

**Comment by jonathon-love** [comment]
oh wow,
@mmarsman1 could you take a look at this one?

**Comment by mmarsman1** [comment]
Hi Mario, 

Thanks for noting issue. 

One reason for this change (which I want to rule out) is that the change occurs due to recomputing the Bayes factor, which, due to sampling, produces slightly different Bayes factor values. 

For instance, using the Tooth Growth dataset supplied with Jasp I have two slightly different results when I  recompute the Bayes factor:

![screen shot 2015-07-08 at 15 47 24](https://cloud.githubusercontent.com/assets/8667548/8571749/d3406682-2588-11e5-8ff8-9f511a4e4d7f.png)

![screen shot 2015-07-08 at 15 47 13](https://cloud.githubusercontent.com/assets/8667548/8571756/d7d0f9c8-2588-11e5-8eee-e5117df00780.png)

Note that these differences are very minor.
They can become slightly larger (but not dramatically so) when computing more complicated models. 

Is this similar to what you found?
If not; could you perhaps make screenshots before and after name-change, or supply the dataset and explain what you did so that I can reproduce the result? 

Thanks!
Maarten

**Comment by jonathon-love** [comment]
ah yes, i'm pretty sure that's it exactly.

i think all you need to do @mmarsman1 is to use the state (and not do a recompute) if the user changes a label.

not really a bug, but will lead to a nicer user experience.

cheers

**Comment by MarioDalmaso** [comment]
Hi Marteen,

yes I'm having exactly the same problem you've described.

Many thanks, cheers
Mario

**Comment by mmarsman1** [comment]
Hi @MarioDalmaso, 

Awesome, always a big relief to see something function as anticipated!
Thanks again for your response; keep them coming! :)

Cheers, 
Maarten

@jonathon-love 
It is the behavior I expect and there is nothing that we can do about it.
To see why, note:
1. This cannot be handled by the state-system, as Jasp has no facilities yet to change a variable, which means that this problem occurs; i) if a user loads a new dataset or ii) if a user replaces one variable with another (which is the same variable but has a different name). 
It is in general not possible to handle i) with the state system (they are separate sessions) and ii) can only be handled by corrupting each analyses where a person replaces one variable with another. This is a bad thing.  

2. I don't think this affects changes in factor-labels, as I only check options during (after) analysis which does not contain the specific factor-labels. Except in Repeated Measures, but how can I tell that this value-label is a label change, and not a variable change (remember that the RM cells are variables)? Again, we don't want to adapt that behaviour, because otherwise we corrupt other valid analyses.

Do I miss anything, or do you concur?

Cheers, 
Maarten

**Comment by jonathon-love** [comment]
i think Mario is talking about *Bayesian Repeated Measures ANOVA* (i infer this, because you can't change the names of factors or levels in *Bayesian ANOVA*)

so this refers to changing the labels in the *Repeated Measures Factors* box (which shouldn't require a recompute)

that's the way i'm interpreting it anyway :P

**Comment by MarioDalmaso** [comment]
That's right, sorry: I mean bayesian rep.measures ANOVA.
Cheers!

**Comment by mmarsman1** [comment]
You mean the Repeated Measures Cells right?
For Jasp (and the analyses) these are variables, so I would expect this behaviour.

Say that I have a RM of two levels (Cells), and have a dataset with three columns: x, y, z.
y and z are the same, except that the names are different (y for the first and z for the second).

So, I specify the analysis with x (level 1) and y (level 2) and get the results.
I don't like my table, so I change the second level by removing variable y with variable z, and Jasp recomputes.

This is what I expect and want from this analysis, as Jasp cannot tell that y and z are the same variable except for the name it uses.

**Comment by mmarsman1** [comment]
Say to tell me that variables and levels have not changed, only the labels that have been used in the Factors box?

**Comment by jonathon-love** [comment]
don't you just compare the values of the options?

**Comment by mmarsman1** [comment]
Yes, but the options change (the variable names are RM Factor 1, etc).
So, the analysis does not know if only the value-labels have changed or the variables has changed.
Any idea how to address that?

Is probably an isolated workaround for RM Anova

**Comment by mmarsman1** [comment]
Never mind, I know what to do, ill try to fix this tonite. 
Good catch guys!

**Comment by MarioDalmaso** [comment]
Thank you, best
Mario

**Comment by jonathon-love** [comment]
just to be clear @MarioDalmaso, this isn't actually a bug. each time you run a stochastic analysis, you will get a slightly different result. in this case, the recomputation of the results following a label change is unnecessary, and so we will make some adjustments to avoid this, and this will provide a slightly nicer user experience; but the more general issue of getting slightly different results each time an analysis is run is unavoidable with these sorts of analyses.

**Comment by MarioDalmaso** [comment]
Thanks @jonathon-love!

**Comment by boutinb** [comment]
This issue is closed due to too long inactivity. Please re-open this issue is this problem still occurs.
