### ISSUE TITLE
"Plotting not possible" for one-sided Bayesian correlation tests 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-desktop#786]
@AlexanderLyNL @mmarsman1 [not vital for next beta release]
When I analyze the big-5 data set using Bayesian correlation matrix, and then select a one-sided analysis, I still get the error message "posterior too peaked". I thought that this was exactly the situation where the Marsman sampler might come to the rescue?!
![image](https://cloud.githubusercontent.com/assets/8603015/8631079/ad06c6f4-2723-11e5-886d-b4aec8d3ae7c.png)

**Comment by AlexanderLyNL** [comment]
Hi EJ, (@quentingronau this might concern you as well)

I think that Quentin and I implemented this correctly. The result shown is based on the exact calculations and I don’t think that the sampler helps here. 

Big-5 Data:
I studied the Big-5 data set and notice that Neuroticism and Extraversion are correlated to each other with a sample correlation coefficient of r=-0.3500786 and n=500. 

Big-5 Analytic:
The exact BFs yield

BF10 = 6.765487e+12
BF+0 = 0.6386719
BF-0 = 1.353097e+13

Hence, this implies that there is hardly any mass on the positive side. However, plotting using .posteriorRhoPlus(n=500, r=-0.35…., rho) does not yield the correct answer. (it is bi-modal). I actually think that the BF+0 of 0.63 is incorrect here, due to the overflow problem, it should be closer to zero. 

Big-5 Analytic Beta fit:
Thus, this lead us to the beta approximation with the following parameters

alpha=185.5933
beta=383.6527

Using dbeta we can then find the mass on the left-hand side of zero, which yields 1. Hence, dbeta assigns zero mass to the posterior of rho from zero to one. Hence, the posterior cannot be normalised when the prior is restricted to lie between zero and one. Alternatively, I tried the numerical integrator which yields 

2.322514e-17 with absolute error < 4.4e-17

Thus, the outcome itself is smaller than the error. I think that this indicates that it is indeed very small. 

Big-5 Analytic CI:
Interestingly, however, I can calculate the 95% credible interval for the model with rho > 0 for which we use qbeta. The 95% positively restricted CI is given by 

2.5% = 0.0001260277
97.5% = 0.0179149983]. 

——

Big-5 Sampler:
The Marsman sampler yields the following Bayes factors

BF10 = 7.682459e+13
BF+0 = 0
BF-0 = Inf

which suggests that there is no posterior mass from zero to one. 

Big-5 Sampler Beta fit:
The posterior beta fit yields the following parameters:

alpha=184.2059
beta=380.5374

This implies that I implemented Marsman method correctly, as it is almost the same as the exact result I found earlier. As before dbeta assigns zero mass to the posterior of rho from zero to one. Hence, the posterior cannot be normalised when the prior is restricted to lie between zero and one. As before, I also tried to numerically integrate the beta fit from zero to one, which yields

3.268406e-17 with absolute error < 6.2e-17

In accordance to the conclusion based on the exact calculations, we see that the normalisation constant  itself is smaller than the error with which this is calculated. think that this indicates that it is indeed very very small. 

Big-5 Sampler CI:
As before I can play around with qbeta and get a 95% credible interval. This time it’s given by

2.5%=0.0001271201 
97.5%=0.0180662955

Conclusion:
I think that the output is correct. Though, I do belief that it would be better to have the error message for each plot individually rather than for all of the plots at once. Furthermore, we might use some approximation to solve the problem, but I think that we can use our valuable time for other issues instead. For instance, models of a somewhat higher complexity; Pearson's correlation is just a simple method with a rate of convergence of \sqrt{n}

**Comment by quentingronau** [comment]
Hi E.J. and Alexander,

Sorry Alexander, this issue is my fault, because I did not make use of the beta approximation for the one-sided case until now (my latest commit changes this). Just to make sure I implemented this correctly: I obtain the area smaller than zero by pbeta(1/2, alpha, beta), because we use a beta distribution which we then scale so that it ranges from -1 to 1, right? For the parameters that Alexander mentioned, this yields an area equal to 1. However, if I use pbeta(1/2, alpha, beta, lower.tail=FALSE) to obtain the area  that is in line with the hypothesis "correlated positively", I obtain 2.322495e-17 and not zero. This enables to plot a posterior, I think, by using

 .scaledBeta(alpha, beta, rho) / pbeta(1/2,  betaA, betaB, lower.tail=FALSE)

and setting the density for rho's smaller than 0 equal to 0. Please correct me if that is wrong.
If this is correct, then it is possible to obtain posterior plots for every variable combination in the Big Five data set. I implemented this (also for the Bayesian Correlation Pairs) and committed it.

Cheers,
Quentin

**Comment by EJWagenmakers** [comment]
Hi Alexander,

Some quick responses:

>Though, I do belief that it would be better to have the error message for
each plot individually rather than for all of the plots at once.

Yes, I completely agree!

> Furthermore, we might use some approximation to solve the problem, but I
think that we can use our valuable time for other issues instead.

Well I also wonder about the message itself. It is not so much that the
posterior is too peaked, but it has to do with normalization, in the sense
that there is virtually no mass consistent with the restriction. Wouldn't
it make more sense to give feedback saying something like: "Plotting not
possible: Almost no posterior mass consistent with the order-restriction"

Note that it cannot be 0 -- there has to be some posterior mass everywhere
from -1 to 1 if there is prior mass there.

Finally, I think I can make this work in JAGS by including the constraint
in the prior. Maybe the Marsman sampler can be adjusted to deal with this
in a similar way.

Cheers,
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by AlexanderLyNL** [comment]
HI EJ,

That sounds like a great plan, you should try it out.

Cheers,
Alexander

**Comment by mmarsman1** [comment]
Yes, that is possible.
There is (in principle) no difficulty, but may require some thinking to make it retain its efficiency (its a very efficient procedure now).

On 13 Jul 2015, at 23:14, AlexanderLyNL <notifications@github.com<mailto:notifications@github.com>> wrote:

HI EJ,

That sounds like a great plan, you should try it out.

Cheers,
Alexander

**Comment by EJWagenmakers** [comment]
Alexander: I cannot stress enough how important it is that these core
analyses work *flawlessly*, such that the code deals with all
eventualities.

Furthermore:

> Hence, this implies that there is hardly any mass on the positive side.
However, plotting using .posteriorRhoPlus(n=500, r=-0.35…., rho) does not
yield the correct answer. (it is bi-modal). I actually think that the BF+0
of 0.63 is incorrect here, due to the overflow problem, it should be closer
to zero.

Yes, this is a problem! So how do we make sure that the user sees the
correct result?

E.J.


********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

**Comment by EJWagenmakers** [comment]
I did this in JAGS and it produces a posterior without too much trouble.
See attached for R code, and a plot of the results. However, the code runs
slowly (but also for the unrestricted case).
E.J.

********************************************
Eric-Jan Wagenmakers
Department of Psychological Methods, room 2.09
University of Amsterdam
Weesperplein 4
1018 XA Amsterdam
The Netherlands

Web: ejwagenmakers.com
Book: bayesmodels.com
Stats: jasp-stats.org
Email: EJ.Wagenmakers@gmail.com
Phone: (+31) 20 525 6420

“Man follows only phantoms.”
Pierre-Simon Laplace, last words
********************************************

On Mon, Jul 13, 2015 at 2:22 PM, Maarten Marsman <notifications@github.com>
wrote:

> Yes, that is possible.
> There is (in principle) no difficulty, but may require some thinking to
> make it retain its efficiency (its a very efficient procedure now).
>
> On 13 Jul 2015, at 23:14, AlexanderLyNL <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> HI EJ,
>
> That sounds like a great plan, you should try it out.
>
> Cheers,
> Alexander
>
> On 13 Jul 2015, at 23:13, EJWagenmakers <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> > Hi Alexander,
> >
> > Some quick responses:
> >
> > >Though, I do belief that it would be better to have the error message
> for
> > each plot individually rather than for all of the plots at once.
> >
> > Yes, I completely agree!
> >
> > > Furthermore, we might use some approximation to solve the problem, but
> I
> > think that we can use our valuable time for other issues instead.
> >
> > Well I also wonder about the message itself. It is not so much that the
> > posterior is too peaked, but it has to do with normalization, in the
> sense
> > that there is virtually no mass consistent with the restriction. Wouldn't
> > it make more sense to give feedback saying something like: "Plotting not
> > possible: Almost no posterior mass consistent with the order-restriction"
> >
> > Note that it cannot be 0 -- there has to be some posterior mass
> everywhere
> > from -1 to 1 if there is prior mass there.
> >
> > Finally, I think I can make this work in JAGS by including the constraint
> > in the prior. Maybe the Marsman sampler can be adjusted to deal with this
> > in a similar way.
> >
> > Cheers,
> > E.J.
> >
> > ********************************************
> > Eric-Jan Wagenmakers
> > Department of Psychological Methods, room 2.09
> > University of Amsterdam
> > Weesperplein 4
> > 1018 XA Amsterdam
> > The Netherlands
> >
> > Web: ejwagenmakers.com<http://ejwagenmakers.com>
> > Book: bayesmodels.com<http://bayesmodels.com>
> > Stats: jasp-stats.org<http://jasp-stats.org>
> > Email: EJ.Wagenmakers@gmail.com<mailto:EJ.Wagenmakers@gmail.com>
> > Phone: (+31) 20 525 6420
> >
> > “Man follows only phantoms.”
> > Pierre-Simon Laplace, last words
> > ********************************************
> >
> > On Mon, Jul 13, 2015 at 3:57 AM, AlexanderLyNL <notifications@github.com
> <mailto:notifications@github.com>>
>
> > wrote:
> >
> > > Hi EJ, (@quentingronau this might concern you as well)
> > >
> > > I think that Quentin and I implemented this correctly. The result
> shown is
> > > based on the exact calculations and I don’t think that the sampler
> helps
> > > here.
> > >
> > > Big-5 Data:
> > > I studied the Big-5 data set and notice that Neuroticism and
> Extraversion
> > > are correlated to each other with a sample correlation coefficient of
> > > r=-0.3500786 and n=500.
> > >
> > > Big-5 Analytic:
> > > The exact BFs yield
> > >
> > > BF10 = 6.765487e+12
> > > BF+0 = 0.6386719
> > > BF-0 = 1.353097e+13
> > >
> > > Hence, this implies that there is hardly any mass on the positive side.
> > > However, plotting using .posteriorRhoPlus(n=500, r=-0.35…., rho) does
> not
> > > yield the correct answer. (it is bi-modal). I actually think that the
> BF+0
> > > of 0.63 is incorrect here, due to the overflow problem, it should be
> closer
> > > to zero.
> > >
> > > Big-5 Analytic Beta fit:
> > > Thus, this lead us to the beta approximation with the following
> parameters
> > >
> > > alpha=185.5933
> > > beta=383.6527
> > >
> > > Using dbeta we can then find the mass on the left-hand side of zero,
> which
> > > yields 1. Hence, dbeta assigns zero mass to the posterior of rho from
> zero
> > > to one. Hence, the posterior cannot be normalised when the prior is
> > > restricted to lie between zero and one. Alternatively, I tried the
> > > numerical integrator which yields
> > >
> > > 2.322514e-17 with absolute error < 4.4e-17
> > >
> > > Thus, the outcome itself is smaller than the error. I think that this
> > > indicates that it is indeed very small.
> > >
> > > Big-5 Analytic CI:
> > > Interestingly, however, I can calculate the 95% credible interval for
> the
> > > model with rho > 0 for which we use qbeta. The 95% positively
> restricted CI
> > > is given by
> > >
> > > 2.5% = 0.0001260277
> > > 97.5% = 0.0179149983].
> > >
> > > ——
> > >
> > > Big-5 Sampler:
> > > The Marsman sampler yields the following Bayes factors
> > >
> > > BF10 = 7.682459e+13
> > > BF+0 = 0
> > > BF-0 = Inf
> > >
> > > which suggests that there is no posterior mass from zero to one.
> > >
> > > Big-5 Sampler Beta fit:
> > > The posterior beta fit yields the following parameters:
> > >
> > > alpha=184.2059
> > > beta=380.5374
> > >
> > > This implies that I implemented Marsman method correctly, as it is
> almost
> > > the same as the exact result I found earlier. As before dbeta assigns
> zero
> > > mass to the posterior of rho from zero to one. Hence, the posterior
> cannot
> > > be normalised when the prior is restricted to lie between zero and
> one. As
> > > before, I also tried to numerically integrate the beta fit from zero to
> > > one, which yields
> > >
> > > 3.268406e-17 with absolute error < 6.2e-17
> > >
> > > In accordance to the conclusion based on the exact calculations, we see
> > > that the normalisation constant itself is smaller than the error with
> which
> > > this is calculated. think that this indicates that it is indeed very
> very
> > > small.
> > >
> > > Big-5 Sampler CI:
> > > As before I can play around with qbeta and get a 95% credible interval.
> > > This time it’s given by
> > >
> > > 2.5%=0.0001271201
> > > 97.5%=0.0180662955
> > >
> > > Conclusion:
> > > I think that the output is correct. Though, I do belief that it would
> be
> > > better to have the error message for each plot individually rather
> than for
> > > all of the plots at once. Furthermore, we might use some approximation
> to
> > > solve the problem, but I think that we can use our valuable time for
> other
> > > issues instead. For instance, models of a somewhat higher complexity;
> > > Pearson's correlation is just a simple method with a rate of
> convergence of
> > > \sqrt{n}
> > >
> > > On 11 Jul 2015, at 01:50, EJWagenmakers <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> > >
> > > > @AlexanderLyNL @mmarsman1 [not vital for next beta release]
> > > > When I analyze the big-5 data set using Bayesian correlation matrix,
> and
> > > then select a one-sided analysis, I still get the error message
> "posterior
> > > too peaked". I thought that this was exactly the situation where the
> > > Marsman sampler might come to the rescue?!
> > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/jasp-stats/jasp-desktop/issues/786#issuecomment-120890155
> >
> > > .
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/jasp-stats/jasp-desktop/issues/786#issuecomment-121061997
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/786#issuecomment-121063611>
> .
>

# Pearson Correlation
model{
  # Data
  for (i in 1:n){
    x[i,1:2] ~ dmnorm(mu[],TI[,])
  }
  # Priors
  mu[1] ~ dnorm(0,.001)
  mu[2] ~ dnorm(0,.001)
  lambda[1] ~ dgamma(.001,.001)
  lambda[2] ~ dgamma(.001,.001)
  rho ~ dunif(0,1) #positive only!
  # Reparameterization
  sigma[1] <- 1/sqrt(lambda[1])
  sigma[2] <- 1/sqrt(lambda[2])
  T[1,1] <- 1/lambda[1]
  T[1,2] <- rho*sigma[1]*sigma[2]
  T[2,1] <- rho*sigma[1]*sigma[2]
  T[2,2] <- 1/lambda[2]
  TI[1:2,1:2] <- inverse(T[1:2,1:2])
}
