### ISSUE TITLE
B Lin Regression: NaN's in BFM

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#810]
<img width="1292" alt="screen shot 2015-07-16 at 6 22 24 pm" src="https://cloud.githubusercontent.com/assets/3240247/8736624/076e4126-2bcf-11e5-994a-1db48435ca8d.png">

**Comment by mmarsman1** [comment]
This appears to be a problem in the BayesFactor package:

> Error in integrate(integrand.regression, lower = 0, upper = Inf, N = N,  : 
  non-finite function value

Treating a dichotomous variable as a continuous covariate does impose some difficulties I guess. I'll commit this to Richard. Haven't we posted something similar before?

**Comment by jonathon-love** [comment]
i think this issue was introduced in #808 , so i don't think it's a BayesFactor issue.

**Comment by mmarsman1** [comment]
It is also part of the old release, so no.

**Comment by mmarsman1** [comment]
maybe tonight, but I really need to stop.

**Comment by mmarsman1** [comment]
Ok. This fixes that problem. 
It does introduce two new problems, which were allready there in the previous version (we just did not see it);  the probabilities were set to 0 previously but this how I initialise them, not how they are computed (!).
Now they are NaN, which is the correct behavior there, I guess, since it is not possible to compute them.

This now also affects the results in the effects table. This ultimately is a design decision, and will need some effort in the near future.
We can do two things; 
- Work with the restricted set of models that can be computed; but this needs to be reported.
- Give NaN's; since one of the models could not be computed (remember its a model averaging computation).
For now option two, but we can work in option one later (which would have my preference).

**Comment by jonathon-love** [comment]
> It is also part of the old release, so no.

if you look at the screenshot above, at the top is an earlier analysis which was performed in 0.7 and saved to a .jasp file. then i've opened the file and run the same analysis, and now BFM's are set to NaN.

similarly, if i revert #808, then BFM's work fine.

so it's definitely #808

**Comment by mmarsman1** [comment]
Yes and I fixed it, see above.
