### ISSUE TITLE
Data export from .jasp files

### ISSUE THREAD

**Issue by jamestripp** [jasp-stats/jasp-desktop#815]
At present, data can be read into jasp from a csv file. Then both an analysis and the data file is saved in a .jasp file. However, I am unable to extract the original data from the .jasp file. Opening the .jasp file as a zip file gives me a data.bin file (which I can't make sense of) and a metadata.json file which seems to give me the data structure.

Can I request a means to export the data? This is particularly important when only a .jasp file is given and additional analysis in other programs is required.

Many thanks,

James Tripp

**Comment by jonathon-love** [comment]
hey @dropmann,

don't know if you want to take this one on; a .csv export. i sometimes like little projects like this as a break from other stuff i'm working on. suit yourself.

**Comment by dropmann** [comment]
yep, i'll have a look at it sometime this week.

**Comment by dropmann** [comment]
So i have the exporting code done, just a few questions. 
1. Is there a way you want to export the missing values? At the moment i'm just push out exactly whats in the dataview.

2. Where did you envision the export button to go? Considering that there is an export button there already, which i suspect will change.

**Comment by jonathon-love** [comment]
> 1. Is there a way you want to export the missing values? At the moment
> i'm just push out exactly whats in the dataview.

i would just push out ... a missing value :)

i.e. a missing value in the b column would be represented as:

a,b,c
1,,3

and Nominal Text

>  1. Where did you envision the export button to go? Considering that
>     there is an export button there already, which i suspect will change.

yeah, i only have preliminary thoughts on this. maybe when you click
export, a dialog pops up with a bunch of options:

Export Results
Export Data

??

did you want to think about it and make a proposal? otherwise i can
think about it.

the commentary stuff is coming along well?

**Comment by jonathon-love** [comment]
> the commentary stuff is coming along well?

haha, don't answer this! i didn't notice the email came from github, and so i was asking questions not related to the issue!

**Comment by dropmann** [comment]
all good.

**Comment by herrlich10** [comment]
I discovered Jasp yesterday and fell in love with it immediately, esp. with the idea that to put data, results, parameters, and notes all together in one place. 

To use it as a way for data persistence and archiving experiment results, I think it would be safer to store things in plain text whenever possible, instead of using custom binary format.
I notice that the numeric results, parameters, and notes are already stored as text in json. Is it possible to also store the original data as json in the jasp file? Or at least provide an option for doing so?

Thanks for creating such a wonderful tool~

**Comment by boutinb** [comment]
Export Data and Export Result are now available.
