### ISSUE TITLE
JASP shouldn't reject backward compatible files

### ISSUE THREAD

**Issue by jonathon-love** [jasp-stats/jasp-desktop#816]
the typical file format version convention is to have version of the form: X.Y.Z

increments to Z indicate backward compatible changes (software can just use file as is; an example of this would be the transition from JASP versions 0.7.0 to 0.7.1; only Z need be incremented)

increments to Y indicate forward compatible changes (software can just use the file as is, but might like to warn the user about a loss of functionality, i.e. when we add annotations; pre-annotation versions should just display the analyses, and leave the annotations out)

increments to X indicate incompatible changes (the software should refuse to open files with higher X values)

(we have an additional massive, which can just be zero)

JASP should follow these conventions (i.e. 0.7.0 shouldn't have rejected files from 0.7.1)

**Comment by dropmann** [comment]
I agree, i am surprised it does, i'll look into it.

**Comment by dropmann** [comment]
I've looked at the code. It doesn't check compatibility using JASP version but using the Data-Archive-Version and JASP-Archive-Version from the manifest. First of all this means that there currently isn't a check for a JASP-content-version (unless we use JASP-Archive-Version to do so, which i don't think is a good idea). Data-Archive-Version is the version of the generic archive format, JASP-Archive-Version is the version of the JASP archive format. It has now been changed so that these two versions go through the check described above, however, i feel like we need a JASP-Content-Version (which is essentially the JASP version it was created on) for comparison to the JASP version doing the opening. There is a 'created-in' tag in the manifest which could be used but it is more of a description rather then a version but that may not matter. Thoughts?

**Comment by jonathon-love** [comment]
> It has now been changed so that these two versions go through the check described above

cool.

> i feel like we need a JASP-Content-Version (which is essentially the JASP version it was created on)

it's good to record the JASP version which created a file, but only for debugging purposes (i.e. we receive a problematic file, and we can track down the version which created it), but the JASP-Archive-Version is the right place for checking compatibility.

**Comment by dropmann** [comment]
So the JASP-Archive-Version tracks analysis variations?

**Comment by dropmann** [comment]
i assumed it would only track JASP format changes.

**Comment by jonathon-love** [comment]
> So the JASP-Archive-Version tracks analysis variations?

for now, we're not tracking analysis variations at all, and that's fine at this stage, but eventually, we'll need to add a version number to each of the individual analyses

**Comment by dropmann** [comment]
JASP-Archive-Version is currently set to 1.0.0, is that fine? Does it need incrementing when we add new analyses? If we are currently not tracking analysis variations i feel like it never needs to change, therefore only on format changes. Which in my head brings me back to my original point of we don't track content (which maybe your point). The previous issue was that we changed the format version from 1.0.0 Alpha 1 to 1.0.0 which it didn't check correctly, but this is fixed now. Am i thinking about this correctly?

**Comment by dropmann** [comment]
I think its late.

**Comment by jonathon-love** [comment]
> I think its late.

*chuckles*

> JASP-Archive-Version is currently set to 1.0.0, is that fine?

yup.

> Does it need incrementing when we add new analyses?

not necessarily, but it may be appropriate.

> If we are currently not tracking analysis variations i feel like it never needs to change, therefore only on format changes

yup, but we had a format change between 0.7, and 0.7.1 (you added the preview stuff), but it was still backwards compatible.

> Which in my head brings me back to my original point of we don't track content

it kinda depends what you mean by content; a format controls content for example.
