### ISSUE TITLE
Frequency Tables just don't appear

### ISSUE THREAD

**Issue by datacarvel** [jasp-stats/jasp-desktop#826]
Hi,

I am unable to see the frequency tables when I ask the software to do so. After loading the dataset, I got into Descriptives, then drag to the right all the variables I need, then I check only the "Display Frequency Tables (nominal and ordinal variables)" option but still nothing appears (sometimes the default Descriptives Statistics appear, though). In fact, "Display Correlation Plot" and "Display Plots" don't always work either, even though I check them and click OK several times. It just does not react. With a previous version of the same dataset I worked at some point but I could not figure how I did this, even though I was glad that it worked.

So I am on Windows 7, 64 bits, 6 gig ram, etc.

**Comment by jonathon-love** [comment]
hi, can you send us a screenshot?

**Comment by datacarvel** [comment]
Sure, here:

One option checked:
![screenshot](https://cloud.githubusercontent.com/assets/13441528/8825590/4cf2351c-304e-11e5-9769-25366cd2bafc.png)

All checked:
![screenshot2](https://cloud.githubusercontent.com/assets/13441528/8825614/72ffb3c4-304e-11e5-9e5d-1d8cb6ad6367.PNG)

**Comment by jonathon-love** [comment]
hi @datacarvel 

1. you're not getting a correlation matrix plot, because none of your variables are continuous; having said that, we do need to provide the user with some explanation for this, and @quentingronau and i are working on it.

2. but i'm pretty puzzled about the frequency tables, and the lack of other plots

can you confirm that you're using the latest 0.7.1 beta 2, and could you send me this data set? my email is jon [at] thon [dot] cc

with thanks

**Comment by jonathon-love** [comment]
i think this is fixed now.
