### ISSUE TITLE
graph for ANOVA

### ISSUE THREAD

**Issue by SibyllePetersen** [jasp-stats/jasp-desktop#853]
Dear JASP team

I just wanted to share analyses with a colleague and realized that while the analyses for a classical repeated measure ANOVA were OK, the graph did not display the descriptive values from the table above. Please see the screenshot attached.

There is a significant main effect and all six values for Group 1 are smaller than the corresponding values for Group 2. The graph seems to display different values. 

I think it is a bug?

Thank you for your great work.

Sibylle

![screenshot problem with graph](https://cloud.githubusercontent.com/assets/13747522/9196787/08acf464-402f-11e5-82f8-1e08f6e016f3.png)

.

**Comment by jonathon-love** [comment]
hi!

thanks for your report.

at a guess, you have only specified two variables to be plotted. if you assign *Certainty* to *Separate plots*, each cell will be plotted.

if that doesn't fix it, can you click on the results (bringing up the options), and send us a screenshot of that? please expand the Descriptives Plots panel so we can see that.

i.e. like the following:

<img width="1377" alt="screen shot 2015-08-11 at 1 50 44 pm" src="https://cloud.githubusercontent.com/assets/3240247/9196885/02f3671e-4030-11e5-8121-507373be9421.png">

**Comment by jonathon-love** [comment]
oh wait, sorry, i completely didn't read your post properly :/

**Comment by jonathon-love** [comment]
can you send me this dataset? my email is: jon at thon dot cc

**Comment by SibyllePetersen** [comment]
Dear Jonathon

Thank you for your fast reply. I send the file right away

Sibylle

**Comment by SibyllePetersen** [comment]
Here is the file. Thank you so much for your help!

Sibylle

Research Unit INSIDE
Institute for Health and Behaviour
Research Group Self-Regulation and Health

UNIVERSITY OF LUXEMBOURG
CAMPUS WALFERDANGE
Route de Diekirch, B.P. 2
L-7220 Walferdange
Building VI - E01 - R.08
Phone:+352 46 66 44 9367


Research Group Health Psychology
KU Leuven
Tiensestraat 102
B-3000 Leuven (Belgium)
http://ppw.kuleuven.be/home/english/research/ogp/sibylle<https://owa.groupware.kuleuven.be/owa/redir.aspx?C=66s9LiIsfkONinrLUzfoFZX4AxYzJtEIZuc9fiaFusRais_eDdvntIYS-ePqQy3ceNOMY1LVhis.&URL=http%3a%2f%2fppw.kuleuven.be%2fhome%2fenglish%2fresearch%2fogp%2fsibylle>
________________________________

**Comment by jonathon-love** [comment]
hey @SibyllePetersen,

unfortunately, github doesn't support attachments, can you send it to my email adress proper: jon at thon dot cc

with thanks

**Comment by raviselker** [comment]
We used the normalised means (calculated so that means of each between-subject group are the same) instead of the regular means for this release. The reason is that we  use these means to calculate the corrected confidence intervals (corrected for the repeated measures, see [Morey, 2008](http://tqmp.org/Content/vol04-2/p061/p061.html)). However, it makes more sense to use the regular means in descriptives plots so the next release will use the same means as the descriptives table.

**Comment by jonathon-love** [comment]
hey @SibyllePetersen 

this should be fixed in the current release 0.7.1.2

**Comment by SibyllePetersen** [comment]
Dear Jonathon

This is great. Thank you so very much for this super fast help!

Have a great day

Sibylle

Research Unit INSIDE
Institute for Health and Behaviour
Research Group Self-Regulation and Health

UNIVERSITY OF LUXEMBOURG
CAMPUS WALFERDANGE
Route de Diekirch, B.P. 2
L-7220 Walferdange
Building VI - E01 - R.08
Phone:+352 46 66 44 9367


Research Group Health Psychology
KU Leuven
Tiensestraat 102
B-3000 Leuven (Belgium)
http://ppw.kuleuven.be/home/english/research/ogp/sibylle<https://owa.groupware.kuleuven.be/owa/redir.aspx?C=66s9LiIsfkONinrLUzfoFZX4AxYzJtEIZuc9fiaFusRais_eDdvntIYS-ePqQy3ceNOMY1LVhis.&URL=http%3a%2f%2fppw.kuleuven.be%2fhome%2fenglish%2fresearch%2fogp%2fsibylle>
________________________________

**Comment by R180** [comment]
Greetings. I wish I had the technical expertise to help with the programming aspects of this project. Lacking such expertise, I endeavor to help the project by providing suggestions. regarding the confidence intervals, I think any adjustment should be an option and not the default. The reason is that, conceptually, there are always multiple confidence intervals to be considered. Not just one. Most of us are satisfied to have each plotted mean include a confidence-interval error-bar for that plotted mean. Loftus and Mason, in contrast, were proposing to plot confidence intervals paerting to the difference between means, but still having the error bar on a mean instead of on a difference between means. The fact is that the confidence interval for a difference between means won't be the same as the confidence interval for the mean. And moreover, the CI for the ifference between means will depend on which difference--a within-subject difference or a between-subject difference--one is considering.  

I think that if the CI error-bar is being plotted around a particular mean, it really ought to be an interval for the mean (and not for differences among means). Or, if one wants confidence intervals for differences between means, those intervals should be plotted around the differences rather than around the means.
