### ISSUE TITLE
Interactivity in plots

### ISSUE THREAD

**Issue by cjalbers** [jasp-stats/jasp-desktop#860]
It would be great, if some kind of interactivity in plots is possible. I encountered this wish in the following setting, but think it is useful in other places as well.

Use for example the Big 5 data by Dolan et al. and make a correlation plot for Agreeableness vs Conscientiousness. It would be great that, when I hover over or click on one of the points in this plot, JASP tells me in some way which observation that is. E.g. when I click in the "outlier" with Agreeableness \approx 3.6 and Consc. < 2, I'd like it if that dot gets highlighted and some message as "observation xxx"-appears, where xxx is the row in the data (out of 500 - so I don't want to look manually) where this observation is.

**Comment by jonathon-love** [comment]
yes, it's a good idea. unfortunately, we use R for all of our plots, and that level of interactivity isn't really practical in R. in the long term i would like to transition our plotting to javascript, as this allows for this kind of interactivity, but this won't happen for a while (a few years). our team are mostly scientists too, who only know R, so that kinda ties my hands a bit too.
good suggestion, and something i'd love to do, but probably not practical in the short or medium term :/

**Comment by cjalbers** [comment]
Some interactivity has already been implemented in various R-packages, such as ggvis (cf. http://ggvis.rstudio.com/ggvis-basics.html ). It seems that you don't need to write the javascript yourself (although it is undoubtly problematic to implement such interactive packages in JASP - I'll be patient... :))

**Comment by jonathon-love** [comment]
> It seems that you don't need to write the javascript yourself

yeah, my expectation is that interactivity provided by ggvis won't be useful beyond a fairly narrow set of use-cases. but i could be wrong.

**Comment by boutinb** [comment]
Due to too long inactivity, this issue is closed.
