### ISSUE TITLE
T-Tests for "wide" data

### ISSUE THREAD

**Issue by slammaster** [jasp-stats/jasp-desktop#985]
It does not seem possible to run a t-test on wide data at the moment (or else I'm just not seeing it).  For example, in the Big 5 sample dataset, you can't run a t-test comparing the difference between Openness and Agreeableness.  This is certainly achievable in R (`t.test(x=Openness,y=Agreeableness)`) and should be considered as an option in JASP.

If I'm just missing it then please let me know, thanks.

**Comment by jonathon-love** [comment]
hi,

we thought about it, but there is some objection among statisticians to unrelated observations being stored in the same row (but you *can* do a paired t-test in wide format; because those observations are related)

further, unrelated data in a single row also complicates outlier exclusion, etc. if you exclude a row, you also exclude an unrelated data point.

it also saves us from having to provide two different t-tests; (long format and wide format); reducing room for confusion; and most people from the SPSS world are only familiar with the long format any way.

so we figured it was probably simpler to only allow independent samples t-tests in long format.

makes sense?

**Comment by slammaster** [comment]
Yeah that's fine, I had a student ask and was surprised it wasn't possible,
but that's an easy enough explanation to force her to re-organize her data.

Thanks,
Sam

On Wed, Sep 16, 2015 at 10:03 AM, Jonathon Love <notifications@github.com>
wrote:

> hi,
>
> we thought about it, but there is some objection among statisticians to
> unrelated observations being stored in the same row (but you *can* do a
> paired t-test in wide format; because those observations are related)
>
> further, unrelated data in a single row also complicates outlier
> exclusion, etc. if you exclude a row, you also exclude an unrelated data
> point.
>
> it also saves us from having to provide two different t-tests; (long
> format and wide format); reducing room for confusion; and most people from
> the SPSS world are only familiar with the long format any way.
>
> so we figured it was probably simpler to only allow independent samples
> t-tests in long format.
>
> makes sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasp-stats/jasp-desktop/issues/985#issuecomment-140735372>
> .
>



-- 
Samuel Alan Stewart, PhD
Assistant Professor, Medical Informatics
Division of Medical Education, Faculty of Medicine, Dalhousie University
Clinical Research Centre | Room C-112A
5849 University Avenue
PO Box 15000 | Halifax NS B3H 4R2 Canada
informatics.medicine.dal.ca
(902) 494-6287
